package com.vccloud.portal.db.dao;

import com.vccloud.portal.db.model.Clientinstallations2;
import com.vccloud.portal.db.model.Clientinstallations2Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Clientinstallations2DAOImpl extends SqlMapClientDaoSupport implements Clientinstallations2DAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public Clientinstallations2DAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public int countByExample(Clientinstallations2Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ClientInstallations2.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public int deleteByExample(Clientinstallations2Example example) {
        int rows = getSqlMapClientTemplate().delete("ClientInstallations2.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void insert(Clientinstallations2 record) {
        getSqlMapClientTemplate().insert("ClientInstallations2.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void insertSelective(Clientinstallations2 record) {
        getSqlMapClientTemplate().insert("ClientInstallations2.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public List selectByExample(Clientinstallations2Example example) {
        List list = getSqlMapClientTemplate().queryForList("ClientInstallations2.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public int updateByExampleSelective(Clientinstallations2 record, Clientinstallations2Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ClientInstallations2.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public int updateByExample(Clientinstallations2 record, Clientinstallations2Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ClientInstallations2.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    private static class UpdateByExampleParms extends Clientinstallations2Example {
        private Object record;

        public UpdateByExampleParms(Object record, Clientinstallations2Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}