package com.vccloud.portal.db.dao;

import com.vccloud.portal.db.model.Clientinstallations2;
import com.vccloud.portal.db.model.Clientinstallations2Example;
import java.util.List;

public interface Clientinstallations2DAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    int countByExample(Clientinstallations2Example example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    int deleteByExample(Clientinstallations2Example example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    void insert(Clientinstallations2 record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    void insertSelective(Clientinstallations2 record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    List selectByExample(Clientinstallations2Example example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    int updateByExampleSelective(Clientinstallations2 record, Clientinstallations2Example example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    int updateByExample(Clientinstallations2 record, Clientinstallations2Example example);
}