package com.vccloud.portal.db.dao;

import java.util.List;

import com.vccloud.portal.db.model.TExtVidyoTenant;
import com.vccloud.portal.db.model.TExtVidyoTenantExample;

public interface TExtVidyoTenantDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int countByExample(TExtVidyoTenantExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int deleteByExample(TExtVidyoTenantExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    Long insert(TExtVidyoTenant record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    Long insertSelective(TExtVidyoTenant record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    List selectByExample(TExtVidyoTenantExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    TExtVidyoTenant selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int updateByExampleSelective(TExtVidyoTenant record, TExtVidyoTenantExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int updateByExample(TExtVidyoTenant record, TExtVidyoTenantExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int updateByPrimaryKeySelective(TExtVidyoTenant record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
	int updateByPrimaryKey(TExtVidyoTenant record);

	public List<TExtVidyoTenant> searchTenants(String keyword, long portalId,
			int startIndex, int pageSize);

	public int countTenants(String keyword, long portalId);
}