package com.vccloud.portal.db.dao;

import com.vccloud.portal.db.model.TExtVidyoOperationAccount;
import com.vccloud.portal.db.model.TExtVidyoOperationAccountExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TExtVidyoOperationAccountDAOImpl extends SqlMapClientDaoSupport implements TExtVidyoOperationAccountDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public TExtVidyoOperationAccountDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int countByExample(TExtVidyoOperationAccountExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_ext_vidyo_operation_account.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int deleteByExample(TExtVidyoOperationAccountExample example) {
        int rows = getSqlMapClientTemplate().delete("t_ext_vidyo_operation_account.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        TExtVidyoOperationAccount key = new TExtVidyoOperationAccount();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_ext_vidyo_operation_account.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public Long insert(TExtVidyoOperationAccount record) {
        Object newKey = getSqlMapClientTemplate().insert("t_ext_vidyo_operation_account.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public Long insertSelective(TExtVidyoOperationAccount record) {
        Object newKey = getSqlMapClientTemplate().insert("t_ext_vidyo_operation_account.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public List selectByExample(TExtVidyoOperationAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_ext_vidyo_operation_account.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public TExtVidyoOperationAccount selectByPrimaryKey(Long id) {
        TExtVidyoOperationAccount key = new TExtVidyoOperationAccount();
        key.setId(id);
        TExtVidyoOperationAccount record = (TExtVidyoOperationAccount) getSqlMapClientTemplate().queryForObject("t_ext_vidyo_operation_account.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int updateByExampleSelective(TExtVidyoOperationAccount record, TExtVidyoOperationAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_operation_account.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int updateByExample(TExtVidyoOperationAccount record, TExtVidyoOperationAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_operation_account.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int updateByPrimaryKeySelective(TExtVidyoOperationAccount record) {
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_operation_account.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int updateByPrimaryKey(TExtVidyoOperationAccount record) {
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_operation_account.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_ext_vidyo_operation_account
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    private static class UpdateByExampleParms extends TExtVidyoOperationAccountExample {
        private Object record;

        public UpdateByExampleParms(Object record, TExtVidyoOperationAccountExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}