package com.vccloud.portal.db.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.vccloud.portal.db.model.TExtVidyoTenant;
import com.vccloud.portal.db.model.TExtVidyoTenantExample;
import com.vccloud.portal.util.CommonUtil;

public class TExtVidyoTenantDAOImpl extends SqlMapClientDaoSupport implements TExtVidyoTenantDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public TExtVidyoTenantDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int countByExample(TExtVidyoTenantExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_ext_vidyo_tenant.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int deleteByExample(TExtVidyoTenantExample example) {
        int rows = getSqlMapClientTemplate().delete("t_ext_vidyo_tenant.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        TExtVidyoTenant key = new TExtVidyoTenant();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_ext_vidyo_tenant.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Long insert(TExtVidyoTenant record) {
        Object newKey = getSqlMapClientTemplate().insert("t_ext_vidyo_tenant.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Long insertSelective(TExtVidyoTenant record) {
        Object newKey = getSqlMapClientTemplate().insert("t_ext_vidyo_tenant.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public List selectByExample(TExtVidyoTenantExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_ext_vidyo_tenant.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public TExtVidyoTenant selectByPrimaryKey(Long id) {
        TExtVidyoTenant key = new TExtVidyoTenant();
        key.setId(id);
        TExtVidyoTenant record = (TExtVidyoTenant) getSqlMapClientTemplate().queryForObject("t_ext_vidyo_tenant.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int updateByExampleSelective(TExtVidyoTenant record, TExtVidyoTenantExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_tenant.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int updateByExample(TExtVidyoTenant record, TExtVidyoTenantExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_tenant.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int updateByPrimaryKeySelective(TExtVidyoTenant record) {
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_tenant.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int updateByPrimaryKey(TExtVidyoTenant record) {
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_tenant.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private static class UpdateByExampleParms extends TExtVidyoTenantExample {
        private Object record;

        public UpdateByExampleParms(Object record, TExtVidyoTenantExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
	}

	public List<TExtVidyoTenant> searchTenants(String keyword, long portalId,
			int startIndex, int pageSize) {
		Map params = new HashMap();
		if (!CommonUtil.isNullOrEmpty(keyword)) {
			params.put("keyword", keyword);
		}
		if (portalId > 0) {
			params.put("portalId", portalId);
		}
		params.put("startIndex", startIndex);
		params.put("pageSize", pageSize);
		List<TExtVidyoTenant> resultList = (List<TExtVidyoTenant>) getSqlMapClientTemplate()
				.queryForList("t_ext_vidyo_tenant.searchTenants", params);
		return resultList;
	}

	public int countTenants(String keyword, long portalId) {
		Map params = new HashMap();
		if (!CommonUtil.isNullOrEmpty(keyword)) {
			params.put("keyword", keyword);
		}
		if (portalId > 0) {
			params.put("portalId", portalId);
		}
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_ext_vidyo_tenant.countTenants", params);
		return count.intValue();
	}
}