package com.vccloud.portal.db.dao;

import java.util.List;

import com.vccloud.portal.db.model.TExtVidyoPortalConfig;
import com.vccloud.portal.db.model.TExtVidyoPortalConfigExample;

public interface TExtVidyoPortalConfigDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    int countByExample(TExtVidyoPortalConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    int deleteByExample(TExtVidyoPortalConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    Long insert(TExtVidyoPortalConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    Long insertSelective(TExtVidyoPortalConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    List selectByExample(TExtVidyoPortalConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    TExtVidyoPortalConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    int updateByExampleSelective(TExtVidyoPortalConfig record, TExtVidyoPortalConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    int updateByExample(TExtVidyoPortalConfig record, TExtVidyoPortalConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    int updateByPrimaryKeySelective(TExtVidyoPortalConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
	int updateByPrimaryKey(TExtVidyoPortalConfig record);

	public List<TExtVidyoPortalConfig> searchTExtVidyoPortalConfigs(
			String keyword, int startIndex, int pageSize);

	public int countTExtVidyoPortalConfigs(String keyword);

	public TExtVidyoPortalConfig getPortalConfigByPortalID(long portalID);
}