package com.vccloud.portal.db.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.vccloud.portal.db.model.TExtVidyoPortalConfig;
import com.vccloud.portal.db.model.TExtVidyoPortalConfigExample;
import com.vccloud.portal.util.CommonUtil;

public class TExtVidyoPortalConfigDAOImpl extends SqlMapClientDaoSupport implements TExtVidyoPortalConfigDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public TExtVidyoPortalConfigDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int countByExample(TExtVidyoPortalConfigExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_ext_vidyo_portal_config.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int deleteByExample(TExtVidyoPortalConfigExample example) {
        int rows = getSqlMapClientTemplate().delete("t_ext_vidyo_portal_config.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        TExtVidyoPortalConfig key = new TExtVidyoPortalConfig();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_ext_vidyo_portal_config.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public Long insert(TExtVidyoPortalConfig record) {
        Object newKey = getSqlMapClientTemplate().insert("t_ext_vidyo_portal_config.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public Long insertSelective(TExtVidyoPortalConfig record) {
        Object newKey = getSqlMapClientTemplate().insert("t_ext_vidyo_portal_config.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public List selectByExample(TExtVidyoPortalConfigExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_ext_vidyo_portal_config.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public TExtVidyoPortalConfig selectByPrimaryKey(Long id) {
        TExtVidyoPortalConfig key = new TExtVidyoPortalConfig();
        key.setId(id);
        TExtVidyoPortalConfig record = (TExtVidyoPortalConfig) getSqlMapClientTemplate().queryForObject("t_ext_vidyo_portal_config.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int updateByExampleSelective(TExtVidyoPortalConfig record, TExtVidyoPortalConfigExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_portal_config.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int updateByExample(TExtVidyoPortalConfig record, TExtVidyoPortalConfigExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_portal_config.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int updateByPrimaryKeySelective(TExtVidyoPortalConfig record) {
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_portal_config.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public int updateByPrimaryKey(TExtVidyoPortalConfig record) {
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_portal_config.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_ext_vidyo_portal_config
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    private static class UpdateByExampleParms extends TExtVidyoPortalConfigExample {
        private Object record;

        public UpdateByExampleParms(Object record, TExtVidyoPortalConfigExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
	}

	public List<TExtVidyoPortalConfig> searchTExtVidyoPortalConfigs(
			String keyword, int startIndex, int pageSize) {
		Map params = new HashMap();
		if (!CommonUtil.isNullOrEmpty(keyword)) {
			params.put("keyword", keyword);
		}
		params.put("startIndex", startIndex);
		params.put("pageSize", pageSize);
		List<TExtVidyoPortalConfig> resultList = (List<TExtVidyoPortalConfig>) getSqlMapClientTemplate()
				.queryForList(
						"t_ext_vidyo_portal_config.searchTExtVidyoPortalConfigs",
						params);
		return resultList;
	}

	public int countTExtVidyoPortalConfigs(String keyword) {
		Map params = new HashMap();
		if (!CommonUtil.isNullOrEmpty(keyword)) {
			params.put("keyword", keyword);
		}
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"t_ext_vidyo_portal_config.countTExtVidyoPortalConfigs",
						params);
		return count.intValue();
	}

	public TExtVidyoPortalConfig getPortalConfigByPortalID(long portalID) {
		Map params = new HashMap();
		params.put("portalID", portalID);
		List<TExtVidyoPortalConfig> resultList = (List<TExtVidyoPortalConfig>) getSqlMapClientTemplate()
				.queryForList(
						"t_ext_vidyo_portal_config.getPortalConfigByPortalID",
						params);
		if (CommonUtil.isNullOrEmpty(resultList)) {
			return null;
		}
		return resultList.get(0);
	}
}