package com.vccloud.portal.db.dao;

import com.vccloud.portal.db.model.TExtVidyoMember;
import com.vccloud.portal.db.model.TExtVidyoMemberExample;
import java.util.List;

public interface TExtVidyoMemberDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int countByExample(TExtVidyoMemberExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int deleteByExample(TExtVidyoMemberExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    Integer insert(TExtVidyoMember record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    Integer insertSelective(TExtVidyoMember record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    List selectByExample(TExtVidyoMemberExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    TExtVidyoMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int updateByExampleSelective(TExtVidyoMember record, TExtVidyoMemberExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int updateByExample(TExtVidyoMember record, TExtVidyoMemberExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    int updateByPrimaryKeySelective(TExtVidyoMember record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
	int updateByPrimaryKey(TExtVidyoMember record);

	public List<TExtVidyoMember> searchMembers(long tenantId, String name,
			int startIndex, int pageSize);

	public int countMembers(long tenantId, String name);
}