package com.vccloud.portal.db.dao;

import com.vccloud.portal.db.model.TExtVidyoPortal;
import com.vccloud.portal.db.model.TExtVidyoPortalExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TExtVidyoPortalDAOImpl extends SqlMapClientDaoSupport implements TExtVidyoPortalDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public TExtVidyoPortalDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public int countByExample(TExtVidyoPortalExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_ext_vidyo_portal.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public int deleteByExample(TExtVidyoPortalExample example) {
        int rows = getSqlMapClientTemplate().delete("t_ext_vidyo_portal.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        TExtVidyoPortal key = new TExtVidyoPortal();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_ext_vidyo_portal.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public Long insert(TExtVidyoPortal record) {
        Object newKey = getSqlMapClientTemplate().insert("t_ext_vidyo_portal.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public Long insertSelective(TExtVidyoPortal record) {
        Object newKey = getSqlMapClientTemplate().insert("t_ext_vidyo_portal.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public List selectByExample(TExtVidyoPortalExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_ext_vidyo_portal.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public TExtVidyoPortal selectByPrimaryKey(Long id) {
        TExtVidyoPortal key = new TExtVidyoPortal();
        key.setId(id);
        TExtVidyoPortal record = (TExtVidyoPortal) getSqlMapClientTemplate().queryForObject("t_ext_vidyo_portal.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public int updateByExampleSelective(TExtVidyoPortal record, TExtVidyoPortalExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_portal.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public int updateByExample(TExtVidyoPortal record, TExtVidyoPortalExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_portal.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public int updateByPrimaryKeySelective(TExtVidyoPortal record) {
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_portal.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public int updateByPrimaryKey(TExtVidyoPortal record) {
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_portal.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    private static class UpdateByExampleParms extends TExtVidyoPortalExample {
        private Object record;

        public UpdateByExampleParms(Object record, TExtVidyoPortalExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}