package com.vccloud.portal.db.dao;

import com.vccloud.portal.db.model.Conferencecall2;
import com.vccloud.portal.db.model.TExtVidyoMember;
import com.vccloud.portal.db.model.TExtVidyoMemberExample;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TExtVidyoMemberDAOImpl extends SqlMapClientDaoSupport implements TExtVidyoMemberDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public TExtVidyoMemberDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int countByExample(TExtVidyoMemberExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_ext_vidyo_member.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int deleteByExample(TExtVidyoMemberExample example) {
        int rows = getSqlMapClientTemplate().delete("t_ext_vidyo_member.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int deleteByPrimaryKey(Integer id) {
        TExtVidyoMember key = new TExtVidyoMember();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_ext_vidyo_member.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer insert(TExtVidyoMember record) {
        Object newKey = getSqlMapClientTemplate().insert("t_ext_vidyo_member.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer insertSelective(TExtVidyoMember record) {
        Object newKey = getSqlMapClientTemplate().insert("t_ext_vidyo_member.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public List selectByExample(TExtVidyoMemberExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_ext_vidyo_member.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public TExtVidyoMember selectByPrimaryKey(Integer id) {
        TExtVidyoMember key = new TExtVidyoMember();
        key.setId(id);
        TExtVidyoMember record = (TExtVidyoMember) getSqlMapClientTemplate().queryForObject("t_ext_vidyo_member.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int updateByExampleSelective(TExtVidyoMember record, TExtVidyoMemberExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_member.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int updateByExample(TExtVidyoMember record, TExtVidyoMemberExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_member.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int updateByPrimaryKeySelective(TExtVidyoMember record) {
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_member.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public int updateByPrimaryKey(TExtVidyoMember record) {
        int rows = getSqlMapClientTemplate().update("t_ext_vidyo_member.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_ext_vidyo_member
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private static class UpdateByExampleParms extends TExtVidyoMemberExample {
        private Object record;

        public UpdateByExampleParms(Object record, TExtVidyoMemberExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
	}

	public List<TExtVidyoMember> searchMembers(long tenantId, String name,
			int startIndex, int pageSize) {
		Map params = new HashMap();
		params.put("tenantId", tenantId);
		params.put("name", name);
		params.put("startIndex", startIndex);
		params.put("pageSize", pageSize);
		params.put("orderByClause", "id desc");
		List<TExtVidyoMember> resultList = (List<TExtVidyoMember>) getSqlMapClientTemplate()
				.queryForList("t_ext_vidyo_member.searchMembers", params);
		return resultList;
	}

	public int countMembers(long tenantId, String name) {
		Map params = new HashMap();
		params.put("tenantId", tenantId);
		params.put("name", name);
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_ext_vidyo_member.countMembers", params);
		return count.intValue();
	}
}