package com.vccloud.portal.db.dao;

import com.vccloud.portal.db.model.TPortalInfo;
import com.vccloud.portal.db.model.TPortalInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TPortalInfoDAOImpl extends SqlMapClientDaoSupport implements TPortalInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public TPortalInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public int countByExample(TPortalInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_portal_info.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public int deleteByExample(TPortalInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("t_portal_info.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public int deleteByPrimaryKey(Long id) {
        TPortalInfo key = new TPortalInfo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_portal_info.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public Long insert(TPortalInfo record) {
        Object newKey = getSqlMapClientTemplate().insert("t_portal_info.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public Long insertSelective(TPortalInfo record) {
        Object newKey = getSqlMapClientTemplate().insert("t_portal_info.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public List selectByExample(TPortalInfoExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_portal_info.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public TPortalInfo selectByPrimaryKey(Long id) {
        TPortalInfo key = new TPortalInfo();
        key.setId(id);
        TPortalInfo record = (TPortalInfo) getSqlMapClientTemplate().queryForObject("t_portal_info.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public int updateByExampleSelective(TPortalInfo record, TPortalInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_portal_info.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public int updateByExample(TPortalInfo record, TPortalInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_portal_info.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public int updateByPrimaryKeySelective(TPortalInfo record) {
        int rows = getSqlMapClientTemplate().update("t_portal_info.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    public int updateByPrimaryKey(TPortalInfo record) {
        int rows = getSqlMapClientTemplate().update("t_portal_info.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_portal_info
     *
     * @ibatorgenerated Tue Mar 18 15:14:46 CST 2014
     */
    private static class UpdateByExampleParms extends TPortalInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, TPortalInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}