package com.vccloud.portal.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Clientinstallations2Example {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public Clientinstallations2Example() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    protected Clientinstallations2Example(Clientinstallations2Example example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ClientInstallations2
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andUsernameIsNull() {
            addCriterion("userName is null");
            return this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("userName is not null");
            return this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("userName =", value, "username");
            return this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("userName <>", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("userName >", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("userName >=", value, "username");
            return this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("userName <", value, "username");
            return this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("userName <=", value, "username");
            return this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("userName like", value, "username");
            return this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("userName not like", value, "username");
            return this;
        }

        public Criteria andUsernameIn(List values) {
            addCriterion("userName in", values, "username");
            return this;
        }

        public Criteria andUsernameNotIn(List values) {
            addCriterion("userName not in", values, "username");
            return this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("userName between", value1, value2, "username");
            return this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("userName not between", value1, value2, "username");
            return this;
        }

        public Criteria andDisplaynameIsNull() {
            addCriterion("displayName is null");
            return this;
        }

        public Criteria andDisplaynameIsNotNull() {
            addCriterion("displayName is not null");
            return this;
        }

        public Criteria andDisplaynameEqualTo(String value) {
            addCriterion("displayName =", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameNotEqualTo(String value) {
            addCriterion("displayName <>", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameGreaterThan(String value) {
            addCriterion("displayName >", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameGreaterThanOrEqualTo(String value) {
            addCriterion("displayName >=", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameLessThan(String value) {
            addCriterion("displayName <", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameLessThanOrEqualTo(String value) {
            addCriterion("displayName <=", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameLike(String value) {
            addCriterion("displayName like", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameNotLike(String value) {
            addCriterion("displayName not like", value, "displayname");
            return this;
        }

        public Criteria andDisplaynameIn(List values) {
            addCriterion("displayName in", values, "displayname");
            return this;
        }

        public Criteria andDisplaynameNotIn(List values) {
            addCriterion("displayName not in", values, "displayname");
            return this;
        }

        public Criteria andDisplaynameBetween(String value1, String value2) {
            addCriterion("displayName between", value1, value2, "displayname");
            return this;
        }

        public Criteria andDisplaynameNotBetween(String value1, String value2) {
            addCriterion("displayName not between", value1, value2, "displayname");
            return this;
        }

        public Criteria andTenantnameIsNull() {
            addCriterion("tenantName is null");
            return this;
        }

        public Criteria andTenantnameIsNotNull() {
            addCriterion("tenantName is not null");
            return this;
        }

        public Criteria andTenantnameEqualTo(String value) {
            addCriterion("tenantName =", value, "tenantname");
            return this;
        }

        public Criteria andTenantnameNotEqualTo(String value) {
            addCriterion("tenantName <>", value, "tenantname");
            return this;
        }

        public Criteria andTenantnameGreaterThan(String value) {
            addCriterion("tenantName >", value, "tenantname");
            return this;
        }

        public Criteria andTenantnameGreaterThanOrEqualTo(String value) {
            addCriterion("tenantName >=", value, "tenantname");
            return this;
        }

        public Criteria andTenantnameLessThan(String value) {
            addCriterion("tenantName <", value, "tenantname");
            return this;
        }

        public Criteria andTenantnameLessThanOrEqualTo(String value) {
            addCriterion("tenantName <=", value, "tenantname");
            return this;
        }

        public Criteria andTenantnameLike(String value) {
            addCriterion("tenantName like", value, "tenantname");
            return this;
        }

        public Criteria andTenantnameNotLike(String value) {
            addCriterion("tenantName not like", value, "tenantname");
            return this;
        }

        public Criteria andTenantnameIn(List values) {
            addCriterion("tenantName in", values, "tenantname");
            return this;
        }

        public Criteria andTenantnameNotIn(List values) {
            addCriterion("tenantName not in", values, "tenantname");
            return this;
        }

        public Criteria andTenantnameBetween(String value1, String value2) {
            addCriterion("tenantName between", value1, value2, "tenantname");
            return this;
        }

        public Criteria andTenantnameNotBetween(String value1, String value2) {
            addCriterion("tenantName not between", value1, value2, "tenantname");
            return this;
        }

        public Criteria andEidIsNull() {
            addCriterion("EID is null");
            return this;
        }

        public Criteria andEidIsNotNull() {
            addCriterion("EID is not null");
            return this;
        }

        public Criteria andEidEqualTo(String value) {
            addCriterion("EID =", value, "eid");
            return this;
        }

        public Criteria andEidNotEqualTo(String value) {
            addCriterion("EID <>", value, "eid");
            return this;
        }

        public Criteria andEidGreaterThan(String value) {
            addCriterion("EID >", value, "eid");
            return this;
        }

        public Criteria andEidGreaterThanOrEqualTo(String value) {
            addCriterion("EID >=", value, "eid");
            return this;
        }

        public Criteria andEidLessThan(String value) {
            addCriterion("EID <", value, "eid");
            return this;
        }

        public Criteria andEidLessThanOrEqualTo(String value) {
            addCriterion("EID <=", value, "eid");
            return this;
        }

        public Criteria andEidLike(String value) {
            addCriterion("EID like", value, "eid");
            return this;
        }

        public Criteria andEidNotLike(String value) {
            addCriterion("EID not like", value, "eid");
            return this;
        }

        public Criteria andEidIn(List values) {
            addCriterion("EID in", values, "eid");
            return this;
        }

        public Criteria andEidNotIn(List values) {
            addCriterion("EID not in", values, "eid");
            return this;
        }

        public Criteria andEidBetween(String value1, String value2) {
            addCriterion("EID between", value1, value2, "eid");
            return this;
        }

        public Criteria andEidNotBetween(String value1, String value2) {
            addCriterion("EID not between", value1, value2, "eid");
            return this;
        }

        public Criteria andIpaddressIsNull() {
            addCriterion("ipAddress is null");
            return this;
        }

        public Criteria andIpaddressIsNotNull() {
            addCriterion("ipAddress is not null");
            return this;
        }

        public Criteria andIpaddressEqualTo(String value) {
            addCriterion("ipAddress =", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotEqualTo(String value) {
            addCriterion("ipAddress <>", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressGreaterThan(String value) {
            addCriterion("ipAddress >", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressGreaterThanOrEqualTo(String value) {
            addCriterion("ipAddress >=", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressLessThan(String value) {
            addCriterion("ipAddress <", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressLessThanOrEqualTo(String value) {
            addCriterion("ipAddress <=", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressLike(String value) {
            addCriterion("ipAddress like", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotLike(String value) {
            addCriterion("ipAddress not like", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressIn(List values) {
            addCriterion("ipAddress in", values, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotIn(List values) {
            addCriterion("ipAddress not in", values, "ipaddress");
            return this;
        }

        public Criteria andIpaddressBetween(String value1, String value2) {
            addCriterion("ipAddress between", value1, value2, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotBetween(String value1, String value2) {
            addCriterion("ipAddress not between", value1, value2, "ipaddress");
            return this;
        }

        public Criteria andHostnameIsNull() {
            addCriterion("hostName is null");
            return this;
        }

        public Criteria andHostnameIsNotNull() {
            addCriterion("hostName is not null");
            return this;
        }

        public Criteria andHostnameEqualTo(String value) {
            addCriterion("hostName =", value, "hostname");
            return this;
        }

        public Criteria andHostnameNotEqualTo(String value) {
            addCriterion("hostName <>", value, "hostname");
            return this;
        }

        public Criteria andHostnameGreaterThan(String value) {
            addCriterion("hostName >", value, "hostname");
            return this;
        }

        public Criteria andHostnameGreaterThanOrEqualTo(String value) {
            addCriterion("hostName >=", value, "hostname");
            return this;
        }

        public Criteria andHostnameLessThan(String value) {
            addCriterion("hostName <", value, "hostname");
            return this;
        }

        public Criteria andHostnameLessThanOrEqualTo(String value) {
            addCriterion("hostName <=", value, "hostname");
            return this;
        }

        public Criteria andHostnameLike(String value) {
            addCriterion("hostName like", value, "hostname");
            return this;
        }

        public Criteria andHostnameNotLike(String value) {
            addCriterion("hostName not like", value, "hostname");
            return this;
        }

        public Criteria andHostnameIn(List values) {
            addCriterion("hostName in", values, "hostname");
            return this;
        }

        public Criteria andHostnameNotIn(List values) {
            addCriterion("hostName not in", values, "hostname");
            return this;
        }

        public Criteria andHostnameBetween(String value1, String value2) {
            addCriterion("hostName between", value1, value2, "hostname");
            return this;
        }

        public Criteria andHostnameNotBetween(String value1, String value2) {
            addCriterion("hostName not between", value1, value2, "hostname");
            return this;
        }

        public Criteria andRoomnameIsNull() {
            addCriterion("roomName is null");
            return this;
        }

        public Criteria andRoomnameIsNotNull() {
            addCriterion("roomName is not null");
            return this;
        }

        public Criteria andRoomnameEqualTo(String value) {
            addCriterion("roomName =", value, "roomname");
            return this;
        }

        public Criteria andRoomnameNotEqualTo(String value) {
            addCriterion("roomName <>", value, "roomname");
            return this;
        }

        public Criteria andRoomnameGreaterThan(String value) {
            addCriterion("roomName >", value, "roomname");
            return this;
        }

        public Criteria andRoomnameGreaterThanOrEqualTo(String value) {
            addCriterion("roomName >=", value, "roomname");
            return this;
        }

        public Criteria andRoomnameLessThan(String value) {
            addCriterion("roomName <", value, "roomname");
            return this;
        }

        public Criteria andRoomnameLessThanOrEqualTo(String value) {
            addCriterion("roomName <=", value, "roomname");
            return this;
        }

        public Criteria andRoomnameLike(String value) {
            addCriterion("roomName like", value, "roomname");
            return this;
        }

        public Criteria andRoomnameNotLike(String value) {
            addCriterion("roomName not like", value, "roomname");
            return this;
        }

        public Criteria andRoomnameIn(List values) {
            addCriterion("roomName in", values, "roomname");
            return this;
        }

        public Criteria andRoomnameNotIn(List values) {
            addCriterion("roomName not in", values, "roomname");
            return this;
        }

        public Criteria andRoomnameBetween(String value1, String value2) {
            addCriterion("roomName between", value1, value2, "roomname");
            return this;
        }

        public Criteria andRoomnameNotBetween(String value1, String value2) {
            addCriterion("roomName not between", value1, value2, "roomname");
            return this;
        }

        public Criteria andRoomownerIsNull() {
            addCriterion("roomOwner is null");
            return this;
        }

        public Criteria andRoomownerIsNotNull() {
            addCriterion("roomOwner is not null");
            return this;
        }

        public Criteria andRoomownerEqualTo(String value) {
            addCriterion("roomOwner =", value, "roomowner");
            return this;
        }

        public Criteria andRoomownerNotEqualTo(String value) {
            addCriterion("roomOwner <>", value, "roomowner");
            return this;
        }

        public Criteria andRoomownerGreaterThan(String value) {
            addCriterion("roomOwner >", value, "roomowner");
            return this;
        }

        public Criteria andRoomownerGreaterThanOrEqualTo(String value) {
            addCriterion("roomOwner >=", value, "roomowner");
            return this;
        }

        public Criteria andRoomownerLessThan(String value) {
            addCriterion("roomOwner <", value, "roomowner");
            return this;
        }

        public Criteria andRoomownerLessThanOrEqualTo(String value) {
            addCriterion("roomOwner <=", value, "roomowner");
            return this;
        }

        public Criteria andRoomownerLike(String value) {
            addCriterion("roomOwner like", value, "roomowner");
            return this;
        }

        public Criteria andRoomownerNotLike(String value) {
            addCriterion("roomOwner not like", value, "roomowner");
            return this;
        }

        public Criteria andRoomownerIn(List values) {
            addCriterion("roomOwner in", values, "roomowner");
            return this;
        }

        public Criteria andRoomownerNotIn(List values) {
            addCriterion("roomOwner not in", values, "roomowner");
            return this;
        }

        public Criteria andRoomownerBetween(String value1, String value2) {
            addCriterion("roomOwner between", value1, value2, "roomowner");
            return this;
        }

        public Criteria andRoomownerNotBetween(String value1, String value2) {
            addCriterion("roomOwner not between", value1, value2, "roomowner");
            return this;
        }

        public Criteria andTimeinstalledIsNull() {
            addCriterion("timeInstalled is null");
            return this;
        }

        public Criteria andTimeinstalledIsNotNull() {
            addCriterion("timeInstalled is not null");
            return this;
        }

        public Criteria andTimeinstalledEqualTo(Date value) {
            addCriterion("timeInstalled =", value, "timeinstalled");
            return this;
        }

        public Criteria andTimeinstalledNotEqualTo(Date value) {
            addCriterion("timeInstalled <>", value, "timeinstalled");
            return this;
        }

        public Criteria andTimeinstalledGreaterThan(Date value) {
            addCriterion("timeInstalled >", value, "timeinstalled");
            return this;
        }

        public Criteria andTimeinstalledGreaterThanOrEqualTo(Date value) {
            addCriterion("timeInstalled >=", value, "timeinstalled");
            return this;
        }

        public Criteria andTimeinstalledLessThan(Date value) {
            addCriterion("timeInstalled <", value, "timeinstalled");
            return this;
        }

        public Criteria andTimeinstalledLessThanOrEqualTo(Date value) {
            addCriterion("timeInstalled <=", value, "timeinstalled");
            return this;
        }

        public Criteria andTimeinstalledIn(List values) {
            addCriterion("timeInstalled in", values, "timeinstalled");
            return this;
        }

        public Criteria andTimeinstalledNotIn(List values) {
            addCriterion("timeInstalled not in", values, "timeinstalled");
            return this;
        }

        public Criteria andTimeinstalledBetween(Date value1, Date value2) {
            addCriterion("timeInstalled between", value1, value2, "timeinstalled");
            return this;
        }

        public Criteria andTimeinstalledNotBetween(Date value1, Date value2) {
            addCriterion("timeInstalled not between", value1, value2, "timeinstalled");
            return this;
        }
    }
}