package com.vccloud.portal.db.model;

import java.util.Date;

public class Clientinstallations2 {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ClientInstallations2.userName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    private String username;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ClientInstallations2.displayName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    private String displayname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ClientInstallations2.tenantName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    private String tenantname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ClientInstallations2.EID
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    private String eid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ClientInstallations2.ipAddress
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    private String ipaddress;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ClientInstallations2.hostName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    private String hostname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ClientInstallations2.roomName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    private String roomname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ClientInstallations2.roomOwner
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    private String roomowner;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ClientInstallations2.timeInstalled
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    private Date timeinstalled;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ClientInstallations2.userName
     *
     * @return the value of ClientInstallations2.userName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ClientInstallations2.userName
     *
     * @param username the value for ClientInstallations2.userName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ClientInstallations2.displayName
     *
     * @return the value of ClientInstallations2.displayName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ClientInstallations2.displayName
     *
     * @param displayname the value for ClientInstallations2.displayName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname == null ? null : displayname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ClientInstallations2.tenantName
     *
     * @return the value of ClientInstallations2.tenantName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public String getTenantname() {
        return tenantname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ClientInstallations2.tenantName
     *
     * @param tenantname the value for ClientInstallations2.tenantName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void setTenantname(String tenantname) {
        this.tenantname = tenantname == null ? null : tenantname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ClientInstallations2.EID
     *
     * @return the value of ClientInstallations2.EID
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ClientInstallations2.EID
     *
     * @param eid the value for ClientInstallations2.EID
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ClientInstallations2.ipAddress
     *
     * @return the value of ClientInstallations2.ipAddress
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ClientInstallations2.ipAddress
     *
     * @param ipaddress the value for ClientInstallations2.ipAddress
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress == null ? null : ipaddress.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ClientInstallations2.hostName
     *
     * @return the value of ClientInstallations2.hostName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ClientInstallations2.hostName
     *
     * @param hostname the value for ClientInstallations2.hostName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void setHostname(String hostname) {
        this.hostname = hostname == null ? null : hostname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ClientInstallations2.roomName
     *
     * @return the value of ClientInstallations2.roomName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public String getRoomname() {
        return roomname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ClientInstallations2.roomName
     *
     * @param roomname the value for ClientInstallations2.roomName
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void setRoomname(String roomname) {
        this.roomname = roomname == null ? null : roomname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ClientInstallations2.roomOwner
     *
     * @return the value of ClientInstallations2.roomOwner
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public String getRoomowner() {
        return roomowner;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ClientInstallations2.roomOwner
     *
     * @param roomowner the value for ClientInstallations2.roomOwner
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void setRoomowner(String roomowner) {
        this.roomowner = roomowner == null ? null : roomowner.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ClientInstallations2.timeInstalled
     *
     * @return the value of ClientInstallations2.timeInstalled
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public Date getTimeinstalled() {
        return timeinstalled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ClientInstallations2.timeInstalled
     *
     * @param timeinstalled the value for ClientInstallations2.timeInstalled
     *
     * @ibatorgenerated Thu Sep 05 15:50:58 CST 2013
     */
    public void setTimeinstalled(Date timeinstalled) {
        this.timeinstalled = timeinstalled;
    }
}