package com.vccloud.portal.db.model;

import java.util.Date;

public class TCdr {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.portal_id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long portalId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.tenant_id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long tenantId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.member_id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long memberId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.date
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Date date;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.year
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long year;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.month
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long month;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.day
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long day;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.week
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long week;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.times_callin
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long timesCallin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.duration_callin
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long durationCallin;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.times_callout
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long timesCallout;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_cdr.duration_callout
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    private Long durationCallout;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.id
     *
     * @return the value of t_cdr.id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.id
     *
     * @param id the value for t_cdr.id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.portal_id
     *
     * @return the value of t_cdr.portal_id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getPortalId() {
        return portalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.portal_id
     *
     * @param portalId the value for t_cdr.portal_id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setPortalId(Long portalId) {
        this.portalId = portalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.tenant_id
     *
     * @return the value of t_cdr.tenant_id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.tenant_id
     *
     * @param tenantId the value for t_cdr.tenant_id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.member_id
     *
     * @return the value of t_cdr.member_id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.member_id
     *
     * @param memberId the value for t_cdr.member_id
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.date
     *
     * @return the value of t_cdr.date
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.date
     *
     * @param date the value for t_cdr.date
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.year
     *
     * @return the value of t_cdr.year
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getYear() {
        return year;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.year
     *
     * @param year the value for t_cdr.year
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setYear(Long year) {
        this.year = year;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.month
     *
     * @return the value of t_cdr.month
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getMonth() {
        return month;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.month
     *
     * @param month the value for t_cdr.month
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setMonth(Long month) {
        this.month = month;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.day
     *
     * @return the value of t_cdr.day
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getDay() {
        return day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.day
     *
     * @param day the value for t_cdr.day
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setDay(Long day) {
        this.day = day;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.week
     *
     * @return the value of t_cdr.week
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getWeek() {
        return week;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.week
     *
     * @param week the value for t_cdr.week
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setWeek(Long week) {
        this.week = week;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.times_callin
     *
     * @return the value of t_cdr.times_callin
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getTimesCallin() {
        return timesCallin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.times_callin
     *
     * @param timesCallin the value for t_cdr.times_callin
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setTimesCallin(Long timesCallin) {
        this.timesCallin = timesCallin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.duration_callin
     *
     * @return the value of t_cdr.duration_callin
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getDurationCallin() {
        return durationCallin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.duration_callin
     *
     * @param durationCallin the value for t_cdr.duration_callin
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setDurationCallin(Long durationCallin) {
        this.durationCallin = durationCallin;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.times_callout
     *
     * @return the value of t_cdr.times_callout
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getTimesCallout() {
        return timesCallout;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.times_callout
     *
     * @param timesCallout the value for t_cdr.times_callout
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setTimesCallout(Long timesCallout) {
        this.timesCallout = timesCallout;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_cdr.duration_callout
     *
     * @return the value of t_cdr.duration_callout
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public Long getDurationCallout() {
        return durationCallout;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_cdr.duration_callout
     *
     * @param durationCallout the value for t_cdr.duration_callout
     *
     * @ibatorgenerated Thu Feb 27 16:42:21 CST 2014
     */
    public void setDurationCallout(Long durationCallout) {
        this.durationCallout = durationCallout;
    }
}