package com.vccloud.portal.db.model;

public class TExtVidyoPortal {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal.id
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal.access_token
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    private String accessToken;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal.portalname
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    private String portalname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal.portalpassword
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    private String portalpassword;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal.portalurl
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    private String portalurl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal.status
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal.reference_id
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    private Long referenceId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal.id
     *
     * @return the value of t_ext_vidyo_portal.id
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal.id
     *
     * @param id the value for t_ext_vidyo_portal.id
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal.access_token
     *
     * @return the value of t_ext_vidyo_portal.access_token
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal.access_token
     *
     * @param accessToken the value for t_ext_vidyo_portal.access_token
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal.portalname
     *
     * @return the value of t_ext_vidyo_portal.portalname
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public String getPortalname() {
        return portalname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal.portalname
     *
     * @param portalname the value for t_ext_vidyo_portal.portalname
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public void setPortalname(String portalname) {
        this.portalname = portalname == null ? null : portalname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal.portalpassword
     *
     * @return the value of t_ext_vidyo_portal.portalpassword
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public String getPortalpassword() {
        return portalpassword;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal.portalpassword
     *
     * @param portalpassword the value for t_ext_vidyo_portal.portalpassword
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public void setPortalpassword(String portalpassword) {
        this.portalpassword = portalpassword == null ? null : portalpassword.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal.portalurl
     *
     * @return the value of t_ext_vidyo_portal.portalurl
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public String getPortalurl() {
        return portalurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal.portalurl
     *
     * @param portalurl the value for t_ext_vidyo_portal.portalurl
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public void setPortalurl(String portalurl) {
        this.portalurl = portalurl == null ? null : portalurl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal.status
     *
     * @return the value of t_ext_vidyo_portal.status
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal.status
     *
     * @param status the value for t_ext_vidyo_portal.status
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal.reference_id
     *
     * @return the value of t_ext_vidyo_portal.reference_id
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public Long getReferenceId() {
        return referenceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal.reference_id
     *
     * @param referenceId the value for t_ext_vidyo_portal.reference_id
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public void setReferenceId(Long referenceId) {
        this.referenceId = referenceId;
    }
}