package com.vccloud.portal.db.model;

public class TExtVidyoPortalConfig {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal_config.id
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal_config.portal_name
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    private String portalName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal_config.portal_url
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    private String portalUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal_config.super_name
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    private String superName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_portal_config.super_password
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    private String superPassword;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal_config.id
     *
     * @return the value of t_ext_vidyo_portal_config.id
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal_config.id
     *
     * @param id the value for t_ext_vidyo_portal_config.id
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal_config.portal_name
     *
     * @return the value of t_ext_vidyo_portal_config.portal_name
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public String getPortalName() {
        return portalName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal_config.portal_name
     *
     * @param portalName the value for t_ext_vidyo_portal_config.portal_name
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public void setPortalName(String portalName) {
        this.portalName = portalName == null ? null : portalName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal_config.portal_url
     *
     * @return the value of t_ext_vidyo_portal_config.portal_url
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public String getPortalUrl() {
        return portalUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal_config.portal_url
     *
     * @param portalUrl the value for t_ext_vidyo_portal_config.portal_url
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public void setPortalUrl(String portalUrl) {
        this.portalUrl = portalUrl == null ? null : portalUrl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal_config.super_name
     *
     * @return the value of t_ext_vidyo_portal_config.super_name
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public String getSuperName() {
        return superName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal_config.super_name
     *
     * @param superName the value for t_ext_vidyo_portal_config.super_name
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public void setSuperName(String superName) {
        this.superName = superName == null ? null : superName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_portal_config.super_password
     *
     * @return the value of t_ext_vidyo_portal_config.super_password
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public String getSuperPassword() {
        return superPassword;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_portal_config.super_password
     *
     * @param superPassword the value for t_ext_vidyo_portal_config.super_password
     *
     * @ibatorgenerated Thu Nov 28 16:55:41 CST 2013
     */
    public void setSuperPassword(String superPassword) {
        this.superPassword = superPassword == null ? null : superPassword.trim();
    }
}