package com.vccloud.portal.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TExtVidyoTenantExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public TExtVidyoTenantExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    protected TExtVidyoTenantExample(TExtVidyoTenantExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_ext_vidyo_tenant
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andAdminNameIsNull() {
            addCriterion("admin_name is null");
            return this;
        }

        public Criteria andAdminNameIsNotNull() {
            addCriterion("admin_name is not null");
            return this;
        }

        public Criteria andAdminNameEqualTo(String value) {
            addCriterion("admin_name =", value, "adminName");
            return this;
        }

        public Criteria andAdminNameNotEqualTo(String value) {
            addCriterion("admin_name <>", value, "adminName");
            return this;
        }

        public Criteria andAdminNameGreaterThan(String value) {
            addCriterion("admin_name >", value, "adminName");
            return this;
        }

        public Criteria andAdminNameGreaterThanOrEqualTo(String value) {
            addCriterion("admin_name >=", value, "adminName");
            return this;
        }

        public Criteria andAdminNameLessThan(String value) {
            addCriterion("admin_name <", value, "adminName");
            return this;
        }

        public Criteria andAdminNameLessThanOrEqualTo(String value) {
            addCriterion("admin_name <=", value, "adminName");
            return this;
        }

        public Criteria andAdminNameLike(String value) {
            addCriterion("admin_name like", value, "adminName");
            return this;
        }

        public Criteria andAdminNameNotLike(String value) {
            addCriterion("admin_name not like", value, "adminName");
            return this;
        }

        public Criteria andAdminNameIn(List values) {
            addCriterion("admin_name in", values, "adminName");
            return this;
        }

        public Criteria andAdminNameNotIn(List values) {
            addCriterion("admin_name not in", values, "adminName");
            return this;
        }

        public Criteria andAdminNameBetween(String value1, String value2) {
            addCriterion("admin_name between", value1, value2, "adminName");
            return this;
        }

        public Criteria andAdminNameNotBetween(String value1, String value2) {
            addCriterion("admin_name not between", value1, value2, "adminName");
            return this;
        }

        public Criteria andAdminPasswordIsNull() {
            addCriterion("admin_password is null");
            return this;
        }

        public Criteria andAdminPasswordIsNotNull() {
            addCriterion("admin_password is not null");
            return this;
        }

        public Criteria andAdminPasswordEqualTo(String value) {
            addCriterion("admin_password =", value, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordNotEqualTo(String value) {
            addCriterion("admin_password <>", value, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordGreaterThan(String value) {
            addCriterion("admin_password >", value, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("admin_password >=", value, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordLessThan(String value) {
            addCriterion("admin_password <", value, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordLessThanOrEqualTo(String value) {
            addCriterion("admin_password <=", value, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordLike(String value) {
            addCriterion("admin_password like", value, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordNotLike(String value) {
            addCriterion("admin_password not like", value, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordIn(List values) {
            addCriterion("admin_password in", values, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordNotIn(List values) {
            addCriterion("admin_password not in", values, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordBetween(String value1, String value2) {
            addCriterion("admin_password between", value1, value2, "adminPassword");
            return this;
        }

        public Criteria andAdminPasswordNotBetween(String value1, String value2) {
            addCriterion("admin_password not between", value1, value2, "adminPassword");
            return this;
        }

        public Criteria andAllowedApiIsNull() {
            addCriterion("allowed_api is null");
            return this;
        }

        public Criteria andAllowedApiIsNotNull() {
            addCriterion("allowed_api is not null");
            return this;
        }

        public Criteria andAllowedApiEqualTo(Boolean value) {
            addCriterion("allowed_api =", value, "allowedApi");
            return this;
        }

        public Criteria andAllowedApiNotEqualTo(Boolean value) {
            addCriterion("allowed_api <>", value, "allowedApi");
            return this;
        }

        public Criteria andAllowedApiGreaterThan(Boolean value) {
            addCriterion("allowed_api >", value, "allowedApi");
            return this;
        }

        public Criteria andAllowedApiGreaterThanOrEqualTo(Boolean value) {
            addCriterion("allowed_api >=", value, "allowedApi");
            return this;
        }

        public Criteria andAllowedApiLessThan(Boolean value) {
            addCriterion("allowed_api <", value, "allowedApi");
            return this;
        }

        public Criteria andAllowedApiLessThanOrEqualTo(Boolean value) {
            addCriterion("allowed_api <=", value, "allowedApi");
            return this;
        }

        public Criteria andAllowedApiIn(List values) {
            addCriterion("allowed_api in", values, "allowedApi");
            return this;
        }

        public Criteria andAllowedApiNotIn(List values) {
            addCriterion("allowed_api not in", values, "allowedApi");
            return this;
        }

        public Criteria andAllowedApiBetween(Boolean value1, Boolean value2) {
            addCriterion("allowed_api between", value1, value2, "allowedApi");
            return this;
        }

        public Criteria andAllowedApiNotBetween(Boolean value1, Boolean value2) {
            addCriterion("allowed_api not between", value1, value2, "allowedApi");
            return this;
        }

        public Criteria andAllowedCdrIsNull() {
            addCriterion("allowed_cdr is null");
            return this;
        }

        public Criteria andAllowedCdrIsNotNull() {
            addCriterion("allowed_cdr is not null");
            return this;
        }

        public Criteria andAllowedCdrEqualTo(Boolean value) {
            addCriterion("allowed_cdr =", value, "allowedCdr");
            return this;
        }

        public Criteria andAllowedCdrNotEqualTo(Boolean value) {
            addCriterion("allowed_cdr <>", value, "allowedCdr");
            return this;
        }

        public Criteria andAllowedCdrGreaterThan(Boolean value) {
            addCriterion("allowed_cdr >", value, "allowedCdr");
            return this;
        }

        public Criteria andAllowedCdrGreaterThanOrEqualTo(Boolean value) {
            addCriterion("allowed_cdr >=", value, "allowedCdr");
            return this;
        }

        public Criteria andAllowedCdrLessThan(Boolean value) {
            addCriterion("allowed_cdr <", value, "allowedCdr");
            return this;
        }

        public Criteria andAllowedCdrLessThanOrEqualTo(Boolean value) {
            addCriterion("allowed_cdr <=", value, "allowedCdr");
            return this;
        }

        public Criteria andAllowedCdrIn(List values) {
            addCriterion("allowed_cdr in", values, "allowedCdr");
            return this;
        }

        public Criteria andAllowedCdrNotIn(List values) {
            addCriterion("allowed_cdr not in", values, "allowedCdr");
            return this;
        }

        public Criteria andAllowedCdrBetween(Boolean value1, Boolean value2) {
            addCriterion("allowed_cdr between", value1, value2, "allowedCdr");
            return this;
        }

        public Criteria andAllowedCdrNotBetween(Boolean value1, Boolean value2) {
            addCriterion("allowed_cdr not between", value1, value2, "allowedCdr");
            return this;
        }

        public Criteria andAllowedGuestIsNull() {
            addCriterion("allowed_guest is null");
            return this;
        }

        public Criteria andAllowedGuestIsNotNull() {
            addCriterion("allowed_guest is not null");
            return this;
        }

        public Criteria andAllowedGuestEqualTo(Boolean value) {
            addCriterion("allowed_guest =", value, "allowedGuest");
            return this;
        }

        public Criteria andAllowedGuestNotEqualTo(Boolean value) {
            addCriterion("allowed_guest <>", value, "allowedGuest");
            return this;
        }

        public Criteria andAllowedGuestGreaterThan(Boolean value) {
            addCriterion("allowed_guest >", value, "allowedGuest");
            return this;
        }

        public Criteria andAllowedGuestGreaterThanOrEqualTo(Boolean value) {
            addCriterion("allowed_guest >=", value, "allowedGuest");
            return this;
        }

        public Criteria andAllowedGuestLessThan(Boolean value) {
            addCriterion("allowed_guest <", value, "allowedGuest");
            return this;
        }

        public Criteria andAllowedGuestLessThanOrEqualTo(Boolean value) {
            addCriterion("allowed_guest <=", value, "allowedGuest");
            return this;
        }

        public Criteria andAllowedGuestIn(List values) {
            addCriterion("allowed_guest in", values, "allowedGuest");
            return this;
        }

        public Criteria andAllowedGuestNotIn(List values) {
            addCriterion("allowed_guest not in", values, "allowedGuest");
            return this;
        }

        public Criteria andAllowedGuestBetween(Boolean value1, Boolean value2) {
            addCriterion("allowed_guest between", value1, value2, "allowedGuest");
            return this;
        }

        public Criteria andAllowedGuestNotBetween(Boolean value1, Boolean value2) {
            addCriterion("allowed_guest not between", value1, value2, "allowedGuest");
            return this;
        }

        public Criteria andAllowIpcInboundIsNull() {
            addCriterion("allow_ipc_inbound is null");
            return this;
        }

        public Criteria andAllowIpcInboundIsNotNull() {
            addCriterion("allow_ipc_inbound is not null");
            return this;
        }

        public Criteria andAllowIpcInboundEqualTo(Boolean value) {
            addCriterion("allow_ipc_inbound =", value, "allowIpcInbound");
            return this;
        }

        public Criteria andAllowIpcInboundNotEqualTo(Boolean value) {
            addCriterion("allow_ipc_inbound <>", value, "allowIpcInbound");
            return this;
        }

        public Criteria andAllowIpcInboundGreaterThan(Boolean value) {
            addCriterion("allow_ipc_inbound >", value, "allowIpcInbound");
            return this;
        }

        public Criteria andAllowIpcInboundGreaterThanOrEqualTo(Boolean value) {
            addCriterion("allow_ipc_inbound >=", value, "allowIpcInbound");
            return this;
        }

        public Criteria andAllowIpcInboundLessThan(Boolean value) {
            addCriterion("allow_ipc_inbound <", value, "allowIpcInbound");
            return this;
        }

        public Criteria andAllowIpcInboundLessThanOrEqualTo(Boolean value) {
            addCriterion("allow_ipc_inbound <=", value, "allowIpcInbound");
            return this;
        }

        public Criteria andAllowIpcInboundIn(List values) {
            addCriterion("allow_ipc_inbound in", values, "allowIpcInbound");
            return this;
        }

        public Criteria andAllowIpcInboundNotIn(List values) {
            addCriterion("allow_ipc_inbound not in", values, "allowIpcInbound");
            return this;
        }

        public Criteria andAllowIpcInboundBetween(Boolean value1, Boolean value2) {
            addCriterion("allow_ipc_inbound between", value1, value2, "allowIpcInbound");
            return this;
        }

        public Criteria andAllowIpcInboundNotBetween(Boolean value1, Boolean value2) {
            addCriterion("allow_ipc_inbound not between", value1, value2, "allowIpcInbound");
            return this;
        }

        public Criteria andAllowIpcOutboundIsNull() {
            addCriterion("allow_ipc_outbound is null");
            return this;
        }

        public Criteria andAllowIpcOutboundIsNotNull() {
            addCriterion("allow_ipc_outbound is not null");
            return this;
        }

        public Criteria andAllowIpcOutboundEqualTo(Boolean value) {
            addCriterion("allow_ipc_outbound =", value, "allowIpcOutbound");
            return this;
        }

        public Criteria andAllowIpcOutboundNotEqualTo(Boolean value) {
            addCriterion("allow_ipc_outbound <>", value, "allowIpcOutbound");
            return this;
        }

        public Criteria andAllowIpcOutboundGreaterThan(Boolean value) {
            addCriterion("allow_ipc_outbound >", value, "allowIpcOutbound");
            return this;
        }

        public Criteria andAllowIpcOutboundGreaterThanOrEqualTo(Boolean value) {
            addCriterion("allow_ipc_outbound >=", value, "allowIpcOutbound");
            return this;
        }

        public Criteria andAllowIpcOutboundLessThan(Boolean value) {
            addCriterion("allow_ipc_outbound <", value, "allowIpcOutbound");
            return this;
        }

        public Criteria andAllowIpcOutboundLessThanOrEqualTo(Boolean value) {
            addCriterion("allow_ipc_outbound <=", value, "allowIpcOutbound");
            return this;
        }

        public Criteria andAllowIpcOutboundIn(List values) {
            addCriterion("allow_ipc_outbound in", values, "allowIpcOutbound");
            return this;
        }

        public Criteria andAllowIpcOutboundNotIn(List values) {
            addCriterion("allow_ipc_outbound not in", values, "allowIpcOutbound");
            return this;
        }

        public Criteria andAllowIpcOutboundBetween(Boolean value1, Boolean value2) {
            addCriterion("allow_ipc_outbound between", value1, value2, "allowIpcOutbound");
            return this;
        }

        public Criteria andAllowIpcOutboundNotBetween(Boolean value1, Boolean value2) {
            addCriterion("allow_ipc_outbound not between", value1, value2, "allowIpcOutbound");
            return this;
        }

        public Criteria andAllowedMobileIsNull() {
            addCriterion("allowed_mobile is null");
            return this;
        }

        public Criteria andAllowedMobileIsNotNull() {
            addCriterion("allowed_mobile is not null");
            return this;
        }

        public Criteria andAllowedMobileEqualTo(Boolean value) {
            addCriterion("allowed_mobile =", value, "allowedMobile");
            return this;
        }

        public Criteria andAllowedMobileNotEqualTo(Boolean value) {
            addCriterion("allowed_mobile <>", value, "allowedMobile");
            return this;
        }

        public Criteria andAllowedMobileGreaterThan(Boolean value) {
            addCriterion("allowed_mobile >", value, "allowedMobile");
            return this;
        }

        public Criteria andAllowedMobileGreaterThanOrEqualTo(Boolean value) {
            addCriterion("allowed_mobile >=", value, "allowedMobile");
            return this;
        }

        public Criteria andAllowedMobileLessThan(Boolean value) {
            addCriterion("allowed_mobile <", value, "allowedMobile");
            return this;
        }

        public Criteria andAllowedMobileLessThanOrEqualTo(Boolean value) {
            addCriterion("allowed_mobile <=", value, "allowedMobile");
            return this;
        }

        public Criteria andAllowedMobileIn(List values) {
            addCriterion("allowed_mobile in", values, "allowedMobile");
            return this;
        }

        public Criteria andAllowedMobileNotIn(List values) {
            addCriterion("allowed_mobile not in", values, "allowedMobile");
            return this;
        }

        public Criteria andAllowedMobileBetween(Boolean value1, Boolean value2) {
            addCriterion("allowed_mobile between", value1, value2, "allowedMobile");
            return this;
        }

        public Criteria andAllowedMobileNotBetween(Boolean value1, Boolean value2) {
            addCriterion("allowed_mobile not between", value1, value2, "allowedMobile");
            return this;
        }

        public Criteria andCdrPasswordIsNull() {
            addCriterion("cdr_password is null");
            return this;
        }

        public Criteria andCdrPasswordIsNotNull() {
            addCriterion("cdr_password is not null");
            return this;
        }

        public Criteria andCdrPasswordEqualTo(String value) {
            addCriterion("cdr_password =", value, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordNotEqualTo(String value) {
            addCriterion("cdr_password <>", value, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordGreaterThan(String value) {
            addCriterion("cdr_password >", value, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("cdr_password >=", value, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordLessThan(String value) {
            addCriterion("cdr_password <", value, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordLessThanOrEqualTo(String value) {
            addCriterion("cdr_password <=", value, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordLike(String value) {
            addCriterion("cdr_password like", value, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordNotLike(String value) {
            addCriterion("cdr_password not like", value, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordIn(List values) {
            addCriterion("cdr_password in", values, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordNotIn(List values) {
            addCriterion("cdr_password not in", values, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordBetween(String value1, String value2) {
            addCriterion("cdr_password between", value1, value2, "cdrPassword");
            return this;
        }

        public Criteria andCdrPasswordNotBetween(String value1, String value2) {
            addCriterion("cdr_password not between", value1, value2, "cdrPassword");
            return this;
        }

        public Criteria andCdrSchedulerTimeIsNull() {
            addCriterion("cdr_scheduler_time is null");
            return this;
        }

        public Criteria andCdrSchedulerTimeIsNotNull() {
            addCriterion("cdr_scheduler_time is not null");
            return this;
        }

        public Criteria andCdrSchedulerTimeEqualTo(Date value) {
            addCriterion("cdr_scheduler_time =", value, "cdrSchedulerTime");
            return this;
        }

        public Criteria andCdrSchedulerTimeNotEqualTo(Date value) {
            addCriterion("cdr_scheduler_time <>", value, "cdrSchedulerTime");
            return this;
        }

        public Criteria andCdrSchedulerTimeGreaterThan(Date value) {
            addCriterion("cdr_scheduler_time >", value, "cdrSchedulerTime");
            return this;
        }

        public Criteria andCdrSchedulerTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cdr_scheduler_time >=", value, "cdrSchedulerTime");
            return this;
        }

        public Criteria andCdrSchedulerTimeLessThan(Date value) {
            addCriterion("cdr_scheduler_time <", value, "cdrSchedulerTime");
            return this;
        }

        public Criteria andCdrSchedulerTimeLessThanOrEqualTo(Date value) {
            addCriterion("cdr_scheduler_time <=", value, "cdrSchedulerTime");
            return this;
        }

        public Criteria andCdrSchedulerTimeIn(List values) {
            addCriterion("cdr_scheduler_time in", values, "cdrSchedulerTime");
            return this;
        }

        public Criteria andCdrSchedulerTimeNotIn(List values) {
            addCriterion("cdr_scheduler_time not in", values, "cdrSchedulerTime");
            return this;
        }

        public Criteria andCdrSchedulerTimeBetween(Date value1, Date value2) {
            addCriterion("cdr_scheduler_time between", value1, value2, "cdrSchedulerTime");
            return this;
        }

        public Criteria andCdrSchedulerTimeNotBetween(Date value1, Date value2) {
            addCriterion("cdr_scheduler_time not between", value1, value2, "cdrSchedulerTime");
            return this;
        }

        public Criteria andCdrSynchroTimeIsNull() {
            addCriterion("cdr_synchro_time is null");
            return this;
        }

        public Criteria andCdrSynchroTimeIsNotNull() {
            addCriterion("cdr_synchro_time is not null");
            return this;
        }

        public Criteria andCdrSynchroTimeEqualTo(Date value) {
            addCriterion("cdr_synchro_time =", value, "cdrSynchroTime");
            return this;
        }

        public Criteria andCdrSynchroTimeNotEqualTo(Date value) {
            addCriterion("cdr_synchro_time <>", value, "cdrSynchroTime");
            return this;
        }

        public Criteria andCdrSynchroTimeGreaterThan(Date value) {
            addCriterion("cdr_synchro_time >", value, "cdrSynchroTime");
            return this;
        }

        public Criteria andCdrSynchroTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cdr_synchro_time >=", value, "cdrSynchroTime");
            return this;
        }

        public Criteria andCdrSynchroTimeLessThan(Date value) {
            addCriterion("cdr_synchro_time <", value, "cdrSynchroTime");
            return this;
        }

        public Criteria andCdrSynchroTimeLessThanOrEqualTo(Date value) {
            addCriterion("cdr_synchro_time <=", value, "cdrSynchroTime");
            return this;
        }

        public Criteria andCdrSynchroTimeIn(List values) {
            addCriterion("cdr_synchro_time in", values, "cdrSynchroTime");
            return this;
        }

        public Criteria andCdrSynchroTimeNotIn(List values) {
            addCriterion("cdr_synchro_time not in", values, "cdrSynchroTime");
            return this;
        }

        public Criteria andCdrSynchroTimeBetween(Date value1, Date value2) {
            addCriterion("cdr_synchro_time between", value1, value2, "cdrSynchroTime");
            return this;
        }

        public Criteria andCdrSynchroTimeNotBetween(Date value1, Date value2) {
            addCriterion("cdr_synchro_time not between", value1, value2, "cdrSynchroTime");
            return this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return this;
        }

        public Criteria andDescriptionIn(List values) {
            addCriterion("description in", values, "description");
            return this;
        }

        public Criteria andDescriptionNotIn(List values) {
            addCriterion("description not in", values, "description");
            return this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return this;
        }

        public Criteria andDialInIsNull() {
            addCriterion("dial_in is null");
            return this;
        }

        public Criteria andDialInIsNotNull() {
            addCriterion("dial_in is not null");
            return this;
        }

        public Criteria andDialInEqualTo(String value) {
            addCriterion("dial_in =", value, "dialIn");
            return this;
        }

        public Criteria andDialInNotEqualTo(String value) {
            addCriterion("dial_in <>", value, "dialIn");
            return this;
        }

        public Criteria andDialInGreaterThan(String value) {
            addCriterion("dial_in >", value, "dialIn");
            return this;
        }

        public Criteria andDialInGreaterThanOrEqualTo(String value) {
            addCriterion("dial_in >=", value, "dialIn");
            return this;
        }

        public Criteria andDialInLessThan(String value) {
            addCriterion("dial_in <", value, "dialIn");
            return this;
        }

        public Criteria andDialInLessThanOrEqualTo(String value) {
            addCriterion("dial_in <=", value, "dialIn");
            return this;
        }

        public Criteria andDialInLike(String value) {
            addCriterion("dial_in like", value, "dialIn");
            return this;
        }

        public Criteria andDialInNotLike(String value) {
            addCriterion("dial_in not like", value, "dialIn");
            return this;
        }

        public Criteria andDialInIn(List values) {
            addCriterion("dial_in in", values, "dialIn");
            return this;
        }

        public Criteria andDialInNotIn(List values) {
            addCriterion("dial_in not in", values, "dialIn");
            return this;
        }

        public Criteria andDialInBetween(String value1, String value2) {
            addCriterion("dial_in between", value1, value2, "dialIn");
            return this;
        }

        public Criteria andDialInNotBetween(String value1, String value2) {
            addCriterion("dial_in not between", value1, value2, "dialIn");
            return this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return this;
        }

        public Criteria andEnabledEqualTo(Boolean value) {
            addCriterion("enabled =", value, "enabled");
            return this;
        }

        public Criteria andEnabledNotEqualTo(Boolean value) {
            addCriterion("enabled <>", value, "enabled");
            return this;
        }

        public Criteria andEnabledGreaterThan(Boolean value) {
            addCriterion("enabled >", value, "enabled");
            return this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enabled >=", value, "enabled");
            return this;
        }

        public Criteria andEnabledLessThan(Boolean value) {
            addCriterion("enabled <", value, "enabled");
            return this;
        }

        public Criteria andEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("enabled <=", value, "enabled");
            return this;
        }

        public Criteria andEnabledIn(List values) {
            addCriterion("enabled in", values, "enabled");
            return this;
        }

        public Criteria andEnabledNotIn(List values) {
            addCriterion("enabled not in", values, "enabled");
            return this;
        }

        public Criteria andEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return this;
        }

        public Criteria andEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return this;
        }

        public Criteria andExtensionPrefixIsNull() {
            addCriterion("extension_prefix is null");
            return this;
        }

        public Criteria andExtensionPrefixIsNotNull() {
            addCriterion("extension_prefix is not null");
            return this;
        }

        public Criteria andExtensionPrefixEqualTo(String value) {
            addCriterion("extension_prefix =", value, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixNotEqualTo(String value) {
            addCriterion("extension_prefix <>", value, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixGreaterThan(String value) {
            addCriterion("extension_prefix >", value, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixGreaterThanOrEqualTo(String value) {
            addCriterion("extension_prefix >=", value, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixLessThan(String value) {
            addCriterion("extension_prefix <", value, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixLessThanOrEqualTo(String value) {
            addCriterion("extension_prefix <=", value, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixLike(String value) {
            addCriterion("extension_prefix like", value, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixNotLike(String value) {
            addCriterion("extension_prefix not like", value, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixIn(List values) {
            addCriterion("extension_prefix in", values, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixNotIn(List values) {
            addCriterion("extension_prefix not in", values, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixBetween(String value1, String value2) {
            addCriterion("extension_prefix between", value1, value2, "extensionPrefix");
            return this;
        }

        public Criteria andExtensionPrefixNotBetween(String value1, String value2) {
            addCriterion("extension_prefix not between", value1, value2, "extensionPrefix");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("name in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("name not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return this;
        }

        public Criteria andNumberExecutiveIsNull() {
            addCriterion("number_executive is null");
            return this;
        }

        public Criteria andNumberExecutiveIsNotNull() {
            addCriterion("number_executive is not null");
            return this;
        }

        public Criteria andNumberExecutiveEqualTo(Integer value) {
            addCriterion("number_executive =", value, "numberExecutive");
            return this;
        }

        public Criteria andNumberExecutiveNotEqualTo(Integer value) {
            addCriterion("number_executive <>", value, "numberExecutive");
            return this;
        }

        public Criteria andNumberExecutiveGreaterThan(Integer value) {
            addCriterion("number_executive >", value, "numberExecutive");
            return this;
        }

        public Criteria andNumberExecutiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_executive >=", value, "numberExecutive");
            return this;
        }

        public Criteria andNumberExecutiveLessThan(Integer value) {
            addCriterion("number_executive <", value, "numberExecutive");
            return this;
        }

        public Criteria andNumberExecutiveLessThanOrEqualTo(Integer value) {
            addCriterion("number_executive <=", value, "numberExecutive");
            return this;
        }

        public Criteria andNumberExecutiveIn(List values) {
            addCriterion("number_executive in", values, "numberExecutive");
            return this;
        }

        public Criteria andNumberExecutiveNotIn(List values) {
            addCriterion("number_executive not in", values, "numberExecutive");
            return this;
        }

        public Criteria andNumberExecutiveBetween(Integer value1, Integer value2) {
            addCriterion("number_executive between", value1, value2, "numberExecutive");
            return this;
        }

        public Criteria andNumberExecutiveNotBetween(Integer value1, Integer value2) {
            addCriterion("number_executive not between", value1, value2, "numberExecutive");
            return this;
        }

        public Criteria andNumberInstallIsNull() {
            addCriterion("number_install is null");
            return this;
        }

        public Criteria andNumberInstallIsNotNull() {
            addCriterion("number_install is not null");
            return this;
        }

        public Criteria andNumberInstallEqualTo(Integer value) {
            addCriterion("number_install =", value, "numberInstall");
            return this;
        }

        public Criteria andNumberInstallNotEqualTo(Integer value) {
            addCriterion("number_install <>", value, "numberInstall");
            return this;
        }

        public Criteria andNumberInstallGreaterThan(Integer value) {
            addCriterion("number_install >", value, "numberInstall");
            return this;
        }

        public Criteria andNumberInstallGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_install >=", value, "numberInstall");
            return this;
        }

        public Criteria andNumberInstallLessThan(Integer value) {
            addCriterion("number_install <", value, "numberInstall");
            return this;
        }

        public Criteria andNumberInstallLessThanOrEqualTo(Integer value) {
            addCriterion("number_install <=", value, "numberInstall");
            return this;
        }

        public Criteria andNumberInstallIn(List values) {
            addCriterion("number_install in", values, "numberInstall");
            return this;
        }

        public Criteria andNumberInstallNotIn(List values) {
            addCriterion("number_install not in", values, "numberInstall");
            return this;
        }

        public Criteria andNumberInstallBetween(Integer value1, Integer value2) {
            addCriterion("number_install between", value1, value2, "numberInstall");
            return this;
        }

        public Criteria andNumberInstallNotBetween(Integer value1, Integer value2) {
            addCriterion("number_install not between", value1, value2, "numberInstall");
            return this;
        }

        public Criteria andNumberLineIsNull() {
            addCriterion("number_line is null");
            return this;
        }

        public Criteria andNumberLineIsNotNull() {
            addCriterion("number_line is not null");
            return this;
        }

        public Criteria andNumberLineEqualTo(Integer value) {
            addCriterion("number_line =", value, "numberLine");
            return this;
        }

        public Criteria andNumberLineNotEqualTo(Integer value) {
            addCriterion("number_line <>", value, "numberLine");
            return this;
        }

        public Criteria andNumberLineGreaterThan(Integer value) {
            addCriterion("number_line >", value, "numberLine");
            return this;
        }

        public Criteria andNumberLineGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_line >=", value, "numberLine");
            return this;
        }

        public Criteria andNumberLineLessThan(Integer value) {
            addCriterion("number_line <", value, "numberLine");
            return this;
        }

        public Criteria andNumberLineLessThanOrEqualTo(Integer value) {
            addCriterion("number_line <=", value, "numberLine");
            return this;
        }

        public Criteria andNumberLineIn(List values) {
            addCriterion("number_line in", values, "numberLine");
            return this;
        }

        public Criteria andNumberLineNotIn(List values) {
            addCriterion("number_line not in", values, "numberLine");
            return this;
        }

        public Criteria andNumberLineBetween(Integer value1, Integer value2) {
            addCriterion("number_line between", value1, value2, "numberLine");
            return this;
        }

        public Criteria andNumberLineNotBetween(Integer value1, Integer value2) {
            addCriterion("number_line not between", value1, value2, "numberLine");
            return this;
        }

        public Criteria andNumberPanoramaIsNull() {
            addCriterion("number_panorama is null");
            return this;
        }

        public Criteria andNumberPanoramaIsNotNull() {
            addCriterion("number_panorama is not null");
            return this;
        }

        public Criteria andNumberPanoramaEqualTo(Integer value) {
            addCriterion("number_panorama =", value, "numberPanorama");
            return this;
        }

        public Criteria andNumberPanoramaNotEqualTo(Integer value) {
            addCriterion("number_panorama <>", value, "numberPanorama");
            return this;
        }

        public Criteria andNumberPanoramaGreaterThan(Integer value) {
            addCriterion("number_panorama >", value, "numberPanorama");
            return this;
        }

        public Criteria andNumberPanoramaGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_panorama >=", value, "numberPanorama");
            return this;
        }

        public Criteria andNumberPanoramaLessThan(Integer value) {
            addCriterion("number_panorama <", value, "numberPanorama");
            return this;
        }

        public Criteria andNumberPanoramaLessThanOrEqualTo(Integer value) {
            addCriterion("number_panorama <=", value, "numberPanorama");
            return this;
        }

        public Criteria andNumberPanoramaIn(List values) {
            addCriterion("number_panorama in", values, "numberPanorama");
            return this;
        }

        public Criteria andNumberPanoramaNotIn(List values) {
            addCriterion("number_panorama not in", values, "numberPanorama");
            return this;
        }

        public Criteria andNumberPanoramaBetween(Integer value1, Integer value2) {
            addCriterion("number_panorama between", value1, value2, "numberPanorama");
            return this;
        }

        public Criteria andNumberPanoramaNotBetween(Integer value1, Integer value2) {
            addCriterion("number_panorama not between", value1, value2, "numberPanorama");
            return this;
        }

        public Criteria andNumberSeatIsNull() {
            addCriterion("number_seat is null");
            return this;
        }

        public Criteria andNumberSeatIsNotNull() {
            addCriterion("number_seat is not null");
            return this;
        }

        public Criteria andNumberSeatEqualTo(Integer value) {
            addCriterion("number_seat =", value, "numberSeat");
            return this;
        }

        public Criteria andNumberSeatNotEqualTo(Integer value) {
            addCriterion("number_seat <>", value, "numberSeat");
            return this;
        }

        public Criteria andNumberSeatGreaterThan(Integer value) {
            addCriterion("number_seat >", value, "numberSeat");
            return this;
        }

        public Criteria andNumberSeatGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_seat >=", value, "numberSeat");
            return this;
        }

        public Criteria andNumberSeatLessThan(Integer value) {
            addCriterion("number_seat <", value, "numberSeat");
            return this;
        }

        public Criteria andNumberSeatLessThanOrEqualTo(Integer value) {
            addCriterion("number_seat <=", value, "numberSeat");
            return this;
        }

        public Criteria andNumberSeatIn(List values) {
            addCriterion("number_seat in", values, "numberSeat");
            return this;
        }

        public Criteria andNumberSeatNotIn(List values) {
            addCriterion("number_seat not in", values, "numberSeat");
            return this;
        }

        public Criteria andNumberSeatBetween(Integer value1, Integer value2) {
            addCriterion("number_seat between", value1, value2, "numberSeat");
            return this;
        }

        public Criteria andNumberSeatNotBetween(Integer value1, Integer value2) {
            addCriterion("number_seat not between", value1, value2, "numberSeat");
            return this;
        }

        public Criteria andPaymentDaysIsNull() {
            addCriterion("payment_days is null");
            return this;
        }

        public Criteria andPaymentDaysIsNotNull() {
            addCriterion("payment_days is not null");
            return this;
        }

        public Criteria andPaymentDaysEqualTo(Integer value) {
            addCriterion("payment_days =", value, "paymentDays");
            return this;
        }

        public Criteria andPaymentDaysNotEqualTo(Integer value) {
            addCriterion("payment_days <>", value, "paymentDays");
            return this;
        }

        public Criteria andPaymentDaysGreaterThan(Integer value) {
            addCriterion("payment_days >", value, "paymentDays");
            return this;
        }

        public Criteria andPaymentDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("payment_days >=", value, "paymentDays");
            return this;
        }

        public Criteria andPaymentDaysLessThan(Integer value) {
            addCriterion("payment_days <", value, "paymentDays");
            return this;
        }

        public Criteria andPaymentDaysLessThanOrEqualTo(Integer value) {
            addCriterion("payment_days <=", value, "paymentDays");
            return this;
        }

        public Criteria andPaymentDaysIn(List values) {
            addCriterion("payment_days in", values, "paymentDays");
            return this;
        }

        public Criteria andPaymentDaysNotIn(List values) {
            addCriterion("payment_days not in", values, "paymentDays");
            return this;
        }

        public Criteria andPaymentDaysBetween(Integer value1, Integer value2) {
            addCriterion("payment_days between", value1, value2, "paymentDays");
            return this;
        }

        public Criteria andPaymentDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("payment_days not between", value1, value2, "paymentDays");
            return this;
        }

        public Criteria andRemotidIsNull() {
            addCriterion("remotId is null");
            return this;
        }

        public Criteria andRemotidIsNotNull() {
            addCriterion("remotId is not null");
            return this;
        }

        public Criteria andRemotidEqualTo(Integer value) {
            addCriterion("remotId =", value, "remotid");
            return this;
        }

        public Criteria andRemotidNotEqualTo(Integer value) {
            addCriterion("remotId <>", value, "remotid");
            return this;
        }

        public Criteria andRemotidGreaterThan(Integer value) {
            addCriterion("remotId >", value, "remotid");
            return this;
        }

        public Criteria andRemotidGreaterThanOrEqualTo(Integer value) {
            addCriterion("remotId >=", value, "remotid");
            return this;
        }

        public Criteria andRemotidLessThan(Integer value) {
            addCriterion("remotId <", value, "remotid");
            return this;
        }

        public Criteria andRemotidLessThanOrEqualTo(Integer value) {
            addCriterion("remotId <=", value, "remotid");
            return this;
        }

        public Criteria andRemotidIn(List values) {
            addCriterion("remotId in", values, "remotid");
            return this;
        }

        public Criteria andRemotidNotIn(List values) {
            addCriterion("remotId not in", values, "remotid");
            return this;
        }

        public Criteria andRemotidBetween(Integer value1, Integer value2) {
            addCriterion("remotId between", value1, value2, "remotid");
            return this;
        }

        public Criteria andRemotidNotBetween(Integer value1, Integer value2) {
            addCriterion("remotId not between", value1, value2, "remotid");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andThirdidIsNull() {
            addCriterion("thirdId is null");
            return this;
        }

        public Criteria andThirdidIsNotNull() {
            addCriterion("thirdId is not null");
            return this;
        }

        public Criteria andThirdidEqualTo(Integer value) {
            addCriterion("thirdId =", value, "thirdid");
            return this;
        }

        public Criteria andThirdidNotEqualTo(Integer value) {
            addCriterion("thirdId <>", value, "thirdid");
            return this;
        }

        public Criteria andThirdidGreaterThan(Integer value) {
            addCriterion("thirdId >", value, "thirdid");
            return this;
        }

        public Criteria andThirdidGreaterThanOrEqualTo(Integer value) {
            addCriterion("thirdId >=", value, "thirdid");
            return this;
        }

        public Criteria andThirdidLessThan(Integer value) {
            addCriterion("thirdId <", value, "thirdid");
            return this;
        }

        public Criteria andThirdidLessThanOrEqualTo(Integer value) {
            addCriterion("thirdId <=", value, "thirdid");
            return this;
        }

        public Criteria andThirdidIn(List values) {
            addCriterion("thirdId in", values, "thirdid");
            return this;
        }

        public Criteria andThirdidNotIn(List values) {
            addCriterion("thirdId not in", values, "thirdid");
            return this;
        }

        public Criteria andThirdidBetween(Integer value1, Integer value2) {
            addCriterion("thirdId between", value1, value2, "thirdid");
            return this;
        }

        public Criteria andThirdidNotBetween(Integer value1, Integer value2) {
            addCriterion("thirdId not between", value1, value2, "thirdid");
            return this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return this;
        }

        public Criteria andUrlIn(List values) {
            addCriterion("url in", values, "url");
            return this;
        }

        public Criteria andUrlNotIn(List values) {
            addCriterion("url not in", values, "url");
            return this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return this;
        }

        public Criteria andVersionIn(List values) {
            addCriterion("version in", values, "version");
            return this;
        }

        public Criteria andVersionNotIn(List values) {
            addCriterion("version not in", values, "version");
            return this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return this;
        }

        public Criteria andVidyoManagerIsNull() {
            addCriterion("vidyo_manager is null");
            return this;
        }

        public Criteria andVidyoManagerIsNotNull() {
            addCriterion("vidyo_manager is not null");
            return this;
        }

        public Criteria andVidyoManagerEqualTo(Integer value) {
            addCriterion("vidyo_manager =", value, "vidyoManager");
            return this;
        }

        public Criteria andVidyoManagerNotEqualTo(Integer value) {
            addCriterion("vidyo_manager <>", value, "vidyoManager");
            return this;
        }

        public Criteria andVidyoManagerGreaterThan(Integer value) {
            addCriterion("vidyo_manager >", value, "vidyoManager");
            return this;
        }

        public Criteria andVidyoManagerGreaterThanOrEqualTo(Integer value) {
            addCriterion("vidyo_manager >=", value, "vidyoManager");
            return this;
        }

        public Criteria andVidyoManagerLessThan(Integer value) {
            addCriterion("vidyo_manager <", value, "vidyoManager");
            return this;
        }

        public Criteria andVidyoManagerLessThanOrEqualTo(Integer value) {
            addCriterion("vidyo_manager <=", value, "vidyoManager");
            return this;
        }

        public Criteria andVidyoManagerIn(List values) {
            addCriterion("vidyo_manager in", values, "vidyoManager");
            return this;
        }

        public Criteria andVidyoManagerNotIn(List values) {
            addCriterion("vidyo_manager not in", values, "vidyoManager");
            return this;
        }

        public Criteria andVidyoManagerBetween(Integer value1, Integer value2) {
            addCriterion("vidyo_manager between", value1, value2, "vidyoManager");
            return this;
        }

        public Criteria andVidyoManagerNotBetween(Integer value1, Integer value2) {
            addCriterion("vidyo_manager not between", value1, value2, "vidyoManager");
            return this;
        }

        public Criteria andVidyoReplayUrlIsNull() {
            addCriterion("vidyo_replay_url is null");
            return this;
        }

        public Criteria andVidyoReplayUrlIsNotNull() {
            addCriterion("vidyo_replay_url is not null");
            return this;
        }

        public Criteria andVidyoReplayUrlEqualTo(String value) {
            addCriterion("vidyo_replay_url =", value, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlNotEqualTo(String value) {
            addCriterion("vidyo_replay_url <>", value, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlGreaterThan(String value) {
            addCriterion("vidyo_replay_url >", value, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlGreaterThanOrEqualTo(String value) {
            addCriterion("vidyo_replay_url >=", value, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlLessThan(String value) {
            addCriterion("vidyo_replay_url <", value, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlLessThanOrEqualTo(String value) {
            addCriterion("vidyo_replay_url <=", value, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlLike(String value) {
            addCriterion("vidyo_replay_url like", value, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlNotLike(String value) {
            addCriterion("vidyo_replay_url not like", value, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlIn(List values) {
            addCriterion("vidyo_replay_url in", values, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlNotIn(List values) {
            addCriterion("vidyo_replay_url not in", values, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlBetween(String value1, String value2) {
            addCriterion("vidyo_replay_url between", value1, value2, "vidyoReplayUrl");
            return this;
        }

        public Criteria andVidyoReplayUrlNotBetween(String value1, String value2) {
            addCriterion("vidyo_replay_url not between", value1, value2, "vidyoReplayUrl");
            return this;
        }

        public Criteria andPortalIdIsNull() {
            addCriterion("portal_id is null");
            return this;
        }

        public Criteria andPortalIdIsNotNull() {
            addCriterion("portal_id is not null");
            return this;
        }

        public Criteria andPortalIdEqualTo(Long value) {
            addCriterion("portal_id =", value, "portalId");
            return this;
        }

        public Criteria andPortalIdNotEqualTo(Long value) {
            addCriterion("portal_id <>", value, "portalId");
            return this;
        }

        public Criteria andPortalIdGreaterThan(Long value) {
            addCriterion("portal_id >", value, "portalId");
            return this;
        }

        public Criteria andPortalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("portal_id >=", value, "portalId");
            return this;
        }

        public Criteria andPortalIdLessThan(Long value) {
            addCriterion("portal_id <", value, "portalId");
            return this;
        }

        public Criteria andPortalIdLessThanOrEqualTo(Long value) {
            addCriterion("portal_id <=", value, "portalId");
            return this;
        }

        public Criteria andPortalIdIn(List values) {
            addCriterion("portal_id in", values, "portalId");
            return this;
        }

        public Criteria andPortalIdNotIn(List values) {
            addCriterion("portal_id not in", values, "portalId");
            return this;
        }

        public Criteria andPortalIdBetween(Long value1, Long value2) {
            addCriterion("portal_id between", value1, value2, "portalId");
            return this;
        }

        public Criteria andPortalIdNotBetween(Long value1, Long value2) {
            addCriterion("portal_id not between", value1, value2, "portalId");
            return this;
        }
    }
}