package com.vccloud.portal.db.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TExtVidyoPortalExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public TExtVidyoPortalExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    protected TExtVidyoPortalExample(TExtVidyoPortalExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_ext_vidyo_portal
     *
     * @ibatorgenerated Mon Dec 02 20:09:05 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andAccessTokenIsNull() {
            addCriterion("access_token is null");
            return this;
        }

        public Criteria andAccessTokenIsNotNull() {
            addCriterion("access_token is not null");
            return this;
        }

        public Criteria andAccessTokenEqualTo(String value) {
            addCriterion("access_token =", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenNotEqualTo(String value) {
            addCriterion("access_token <>", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenGreaterThan(String value) {
            addCriterion("access_token >", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("access_token >=", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenLessThan(String value) {
            addCriterion("access_token <", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("access_token <=", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenLike(String value) {
            addCriterion("access_token like", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenNotLike(String value) {
            addCriterion("access_token not like", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenIn(List values) {
            addCriterion("access_token in", values, "accessToken");
            return this;
        }

        public Criteria andAccessTokenNotIn(List values) {
            addCriterion("access_token not in", values, "accessToken");
            return this;
        }

        public Criteria andAccessTokenBetween(String value1, String value2) {
            addCriterion("access_token between", value1, value2, "accessToken");
            return this;
        }

        public Criteria andAccessTokenNotBetween(String value1, String value2) {
            addCriterion("access_token not between", value1, value2, "accessToken");
            return this;
        }

        public Criteria andPortalnameIsNull() {
            addCriterion("portalname is null");
            return this;
        }

        public Criteria andPortalnameIsNotNull() {
            addCriterion("portalname is not null");
            return this;
        }

        public Criteria andPortalnameEqualTo(String value) {
            addCriterion("portalname =", value, "portalname");
            return this;
        }

        public Criteria andPortalnameNotEqualTo(String value) {
            addCriterion("portalname <>", value, "portalname");
            return this;
        }

        public Criteria andPortalnameGreaterThan(String value) {
            addCriterion("portalname >", value, "portalname");
            return this;
        }

        public Criteria andPortalnameGreaterThanOrEqualTo(String value) {
            addCriterion("portalname >=", value, "portalname");
            return this;
        }

        public Criteria andPortalnameLessThan(String value) {
            addCriterion("portalname <", value, "portalname");
            return this;
        }

        public Criteria andPortalnameLessThanOrEqualTo(String value) {
            addCriterion("portalname <=", value, "portalname");
            return this;
        }

        public Criteria andPortalnameLike(String value) {
            addCriterion("portalname like", value, "portalname");
            return this;
        }

        public Criteria andPortalnameNotLike(String value) {
            addCriterion("portalname not like", value, "portalname");
            return this;
        }

        public Criteria andPortalnameIn(List values) {
            addCriterion("portalname in", values, "portalname");
            return this;
        }

        public Criteria andPortalnameNotIn(List values) {
            addCriterion("portalname not in", values, "portalname");
            return this;
        }

        public Criteria andPortalnameBetween(String value1, String value2) {
            addCriterion("portalname between", value1, value2, "portalname");
            return this;
        }

        public Criteria andPortalnameNotBetween(String value1, String value2) {
            addCriterion("portalname not between", value1, value2, "portalname");
            return this;
        }

        public Criteria andPortalpasswordIsNull() {
            addCriterion("portalpassword is null");
            return this;
        }

        public Criteria andPortalpasswordIsNotNull() {
            addCriterion("portalpassword is not null");
            return this;
        }

        public Criteria andPortalpasswordEqualTo(String value) {
            addCriterion("portalpassword =", value, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordNotEqualTo(String value) {
            addCriterion("portalpassword <>", value, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordGreaterThan(String value) {
            addCriterion("portalpassword >", value, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("portalpassword >=", value, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordLessThan(String value) {
            addCriterion("portalpassword <", value, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordLessThanOrEqualTo(String value) {
            addCriterion("portalpassword <=", value, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordLike(String value) {
            addCriterion("portalpassword like", value, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordNotLike(String value) {
            addCriterion("portalpassword not like", value, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordIn(List values) {
            addCriterion("portalpassword in", values, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordNotIn(List values) {
            addCriterion("portalpassword not in", values, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordBetween(String value1, String value2) {
            addCriterion("portalpassword between", value1, value2, "portalpassword");
            return this;
        }

        public Criteria andPortalpasswordNotBetween(String value1, String value2) {
            addCriterion("portalpassword not between", value1, value2, "portalpassword");
            return this;
        }

        public Criteria andPortalurlIsNull() {
            addCriterion("portalurl is null");
            return this;
        }

        public Criteria andPortalurlIsNotNull() {
            addCriterion("portalurl is not null");
            return this;
        }

        public Criteria andPortalurlEqualTo(String value) {
            addCriterion("portalurl =", value, "portalurl");
            return this;
        }

        public Criteria andPortalurlNotEqualTo(String value) {
            addCriterion("portalurl <>", value, "portalurl");
            return this;
        }

        public Criteria andPortalurlGreaterThan(String value) {
            addCriterion("portalurl >", value, "portalurl");
            return this;
        }

        public Criteria andPortalurlGreaterThanOrEqualTo(String value) {
            addCriterion("portalurl >=", value, "portalurl");
            return this;
        }

        public Criteria andPortalurlLessThan(String value) {
            addCriterion("portalurl <", value, "portalurl");
            return this;
        }

        public Criteria andPortalurlLessThanOrEqualTo(String value) {
            addCriterion("portalurl <=", value, "portalurl");
            return this;
        }

        public Criteria andPortalurlLike(String value) {
            addCriterion("portalurl like", value, "portalurl");
            return this;
        }

        public Criteria andPortalurlNotLike(String value) {
            addCriterion("portalurl not like", value, "portalurl");
            return this;
        }

        public Criteria andPortalurlIn(List values) {
            addCriterion("portalurl in", values, "portalurl");
            return this;
        }

        public Criteria andPortalurlNotIn(List values) {
            addCriterion("portalurl not in", values, "portalurl");
            return this;
        }

        public Criteria andPortalurlBetween(String value1, String value2) {
            addCriterion("portalurl between", value1, value2, "portalurl");
            return this;
        }

        public Criteria andPortalurlNotBetween(String value1, String value2) {
            addCriterion("portalurl not between", value1, value2, "portalurl");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andReferenceIdIsNull() {
            addCriterion("reference_id is null");
            return this;
        }

        public Criteria andReferenceIdIsNotNull() {
            addCriterion("reference_id is not null");
            return this;
        }

        public Criteria andReferenceIdEqualTo(Long value) {
            addCriterion("reference_id =", value, "referenceId");
            return this;
        }

        public Criteria andReferenceIdNotEqualTo(Long value) {
            addCriterion("reference_id <>", value, "referenceId");
            return this;
        }

        public Criteria andReferenceIdGreaterThan(Long value) {
            addCriterion("reference_id >", value, "referenceId");
            return this;
        }

        public Criteria andReferenceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("reference_id >=", value, "referenceId");
            return this;
        }

        public Criteria andReferenceIdLessThan(Long value) {
            addCriterion("reference_id <", value, "referenceId");
            return this;
        }

        public Criteria andReferenceIdLessThanOrEqualTo(Long value) {
            addCriterion("reference_id <=", value, "referenceId");
            return this;
        }

        public Criteria andReferenceIdIn(List values) {
            addCriterion("reference_id in", values, "referenceId");
            return this;
        }

        public Criteria andReferenceIdNotIn(List values) {
            addCriterion("reference_id not in", values, "referenceId");
            return this;
        }

        public Criteria andReferenceIdBetween(Long value1, Long value2) {
            addCriterion("reference_id between", value1, value2, "referenceId");
            return this;
        }

        public Criteria andReferenceIdNotBetween(Long value1, Long value2) {
            addCriterion("reference_id not between", value1, value2, "referenceId");
            return this;
        }
    }
}