package com.vccloud.portal.db.model;

import java.util.Date;

public class TExtVidyoTenant {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.admin_name
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String adminName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.admin_password
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String adminPassword;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.allowed_api
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Boolean allowedApi;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.allowed_cdr
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Boolean allowedCdr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.allowed_guest
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Boolean allowedGuest;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.allow_ipc_inbound
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Boolean allowIpcInbound;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.allow_ipc_outbound
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Boolean allowIpcOutbound;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.allowed_mobile
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Boolean allowedMobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.cdr_password
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String cdrPassword;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.cdr_scheduler_time
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Date cdrSchedulerTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.cdr_synchro_time
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Date cdrSynchroTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.description
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.dial_in
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String dialIn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.enabled
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Boolean enabled;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.extension_prefix
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String extensionPrefix;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.name
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.number_executive
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer numberExecutive;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.number_install
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer numberInstall;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.number_line
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer numberLine;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.number_panorama
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer numberPanorama;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.number_seat
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer numberSeat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.payment_days
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer paymentDays;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.remotId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer remotid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.status
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.thirdId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer thirdid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.url
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String url;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.version
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer version;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.vidyo_manager
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer vidyoManager;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.vidyo_replay_url
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String vidyoReplayUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_tenant.portal_id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Long portalId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.id
     *
     * @return the value of t_ext_vidyo_tenant.id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.id
     *
     * @param id the value for t_ext_vidyo_tenant.id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.admin_name
     *
     * @return the value of t_ext_vidyo_tenant.admin_name
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.admin_name
     *
     * @param adminName the value for t_ext_vidyo_tenant.admin_name
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.admin_password
     *
     * @return the value of t_ext_vidyo_tenant.admin_password
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.admin_password
     *
     * @param adminPassword the value for t_ext_vidyo_tenant.admin_password
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.allowed_api
     *
     * @return the value of t_ext_vidyo_tenant.allowed_api
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Boolean getAllowedApi() {
        return allowedApi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.allowed_api
     *
     * @param allowedApi the value for t_ext_vidyo_tenant.allowed_api
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setAllowedApi(Boolean allowedApi) {
        this.allowedApi = allowedApi;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.allowed_cdr
     *
     * @return the value of t_ext_vidyo_tenant.allowed_cdr
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Boolean getAllowedCdr() {
        return allowedCdr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.allowed_cdr
     *
     * @param allowedCdr the value for t_ext_vidyo_tenant.allowed_cdr
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setAllowedCdr(Boolean allowedCdr) {
        this.allowedCdr = allowedCdr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.allowed_guest
     *
     * @return the value of t_ext_vidyo_tenant.allowed_guest
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Boolean getAllowedGuest() {
        return allowedGuest;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.allowed_guest
     *
     * @param allowedGuest the value for t_ext_vidyo_tenant.allowed_guest
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setAllowedGuest(Boolean allowedGuest) {
        this.allowedGuest = allowedGuest;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.allow_ipc_inbound
     *
     * @return the value of t_ext_vidyo_tenant.allow_ipc_inbound
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Boolean getAllowIpcInbound() {
        return allowIpcInbound;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.allow_ipc_inbound
     *
     * @param allowIpcInbound the value for t_ext_vidyo_tenant.allow_ipc_inbound
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setAllowIpcInbound(Boolean allowIpcInbound) {
        this.allowIpcInbound = allowIpcInbound;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.allow_ipc_outbound
     *
     * @return the value of t_ext_vidyo_tenant.allow_ipc_outbound
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Boolean getAllowIpcOutbound() {
        return allowIpcOutbound;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.allow_ipc_outbound
     *
     * @param allowIpcOutbound the value for t_ext_vidyo_tenant.allow_ipc_outbound
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setAllowIpcOutbound(Boolean allowIpcOutbound) {
        this.allowIpcOutbound = allowIpcOutbound;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.allowed_mobile
     *
     * @return the value of t_ext_vidyo_tenant.allowed_mobile
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Boolean getAllowedMobile() {
        return allowedMobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.allowed_mobile
     *
     * @param allowedMobile the value for t_ext_vidyo_tenant.allowed_mobile
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setAllowedMobile(Boolean allowedMobile) {
        this.allowedMobile = allowedMobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.cdr_password
     *
     * @return the value of t_ext_vidyo_tenant.cdr_password
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getCdrPassword() {
        return cdrPassword;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.cdr_password
     *
     * @param cdrPassword the value for t_ext_vidyo_tenant.cdr_password
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setCdrPassword(String cdrPassword) {
        this.cdrPassword = cdrPassword == null ? null : cdrPassword.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.cdr_scheduler_time
     *
     * @return the value of t_ext_vidyo_tenant.cdr_scheduler_time
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Date getCdrSchedulerTime() {
        return cdrSchedulerTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.cdr_scheduler_time
     *
     * @param cdrSchedulerTime the value for t_ext_vidyo_tenant.cdr_scheduler_time
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setCdrSchedulerTime(Date cdrSchedulerTime) {
        this.cdrSchedulerTime = cdrSchedulerTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.cdr_synchro_time
     *
     * @return the value of t_ext_vidyo_tenant.cdr_synchro_time
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Date getCdrSynchroTime() {
        return cdrSynchroTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.cdr_synchro_time
     *
     * @param cdrSynchroTime the value for t_ext_vidyo_tenant.cdr_synchro_time
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setCdrSynchroTime(Date cdrSynchroTime) {
        this.cdrSynchroTime = cdrSynchroTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.description
     *
     * @return the value of t_ext_vidyo_tenant.description
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.description
     *
     * @param description the value for t_ext_vidyo_tenant.description
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.dial_in
     *
     * @return the value of t_ext_vidyo_tenant.dial_in
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getDialIn() {
        return dialIn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.dial_in
     *
     * @param dialIn the value for t_ext_vidyo_tenant.dial_in
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setDialIn(String dialIn) {
        this.dialIn = dialIn == null ? null : dialIn.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.enabled
     *
     * @return the value of t_ext_vidyo_tenant.enabled
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.enabled
     *
     * @param enabled the value for t_ext_vidyo_tenant.enabled
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.extension_prefix
     *
     * @return the value of t_ext_vidyo_tenant.extension_prefix
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getExtensionPrefix() {
        return extensionPrefix;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.extension_prefix
     *
     * @param extensionPrefix the value for t_ext_vidyo_tenant.extension_prefix
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setExtensionPrefix(String extensionPrefix) {
        this.extensionPrefix = extensionPrefix == null ? null : extensionPrefix.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.name
     *
     * @return the value of t_ext_vidyo_tenant.name
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.name
     *
     * @param name the value for t_ext_vidyo_tenant.name
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.number_executive
     *
     * @return the value of t_ext_vidyo_tenant.number_executive
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getNumberExecutive() {
        return numberExecutive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.number_executive
     *
     * @param numberExecutive the value for t_ext_vidyo_tenant.number_executive
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setNumberExecutive(Integer numberExecutive) {
        this.numberExecutive = numberExecutive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.number_install
     *
     * @return the value of t_ext_vidyo_tenant.number_install
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getNumberInstall() {
        return numberInstall;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.number_install
     *
     * @param numberInstall the value for t_ext_vidyo_tenant.number_install
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setNumberInstall(Integer numberInstall) {
        this.numberInstall = numberInstall;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.number_line
     *
     * @return the value of t_ext_vidyo_tenant.number_line
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getNumberLine() {
        return numberLine;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.number_line
     *
     * @param numberLine the value for t_ext_vidyo_tenant.number_line
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setNumberLine(Integer numberLine) {
        this.numberLine = numberLine;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.number_panorama
     *
     * @return the value of t_ext_vidyo_tenant.number_panorama
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getNumberPanorama() {
        return numberPanorama;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.number_panorama
     *
     * @param numberPanorama the value for t_ext_vidyo_tenant.number_panorama
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setNumberPanorama(Integer numberPanorama) {
        this.numberPanorama = numberPanorama;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.number_seat
     *
     * @return the value of t_ext_vidyo_tenant.number_seat
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getNumberSeat() {
        return numberSeat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.number_seat
     *
     * @param numberSeat the value for t_ext_vidyo_tenant.number_seat
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setNumberSeat(Integer numberSeat) {
        this.numberSeat = numberSeat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.payment_days
     *
     * @return the value of t_ext_vidyo_tenant.payment_days
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getPaymentDays() {
        return paymentDays;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.payment_days
     *
     * @param paymentDays the value for t_ext_vidyo_tenant.payment_days
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setPaymentDays(Integer paymentDays) {
        this.paymentDays = paymentDays;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.remotId
     *
     * @return the value of t_ext_vidyo_tenant.remotId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getRemotid() {
        return remotid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.remotId
     *
     * @param remotid the value for t_ext_vidyo_tenant.remotId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setRemotid(Integer remotid) {
        this.remotid = remotid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.status
     *
     * @return the value of t_ext_vidyo_tenant.status
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.status
     *
     * @param status the value for t_ext_vidyo_tenant.status
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.thirdId
     *
     * @return the value of t_ext_vidyo_tenant.thirdId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getThirdid() {
        return thirdid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.thirdId
     *
     * @param thirdid the value for t_ext_vidyo_tenant.thirdId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setThirdid(Integer thirdid) {
        this.thirdid = thirdid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.url
     *
     * @return the value of t_ext_vidyo_tenant.url
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.url
     *
     * @param url the value for t_ext_vidyo_tenant.url
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.version
     *
     * @return the value of t_ext_vidyo_tenant.version
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.version
     *
     * @param version the value for t_ext_vidyo_tenant.version
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.vidyo_manager
     *
     * @return the value of t_ext_vidyo_tenant.vidyo_manager
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getVidyoManager() {
        return vidyoManager;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.vidyo_manager
     *
     * @param vidyoManager the value for t_ext_vidyo_tenant.vidyo_manager
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setVidyoManager(Integer vidyoManager) {
        this.vidyoManager = vidyoManager;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.vidyo_replay_url
     *
     * @return the value of t_ext_vidyo_tenant.vidyo_replay_url
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getVidyoReplayUrl() {
        return vidyoReplayUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.vidyo_replay_url
     *
     * @param vidyoReplayUrl the value for t_ext_vidyo_tenant.vidyo_replay_url
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setVidyoReplayUrl(String vidyoReplayUrl) {
        this.vidyoReplayUrl = vidyoReplayUrl == null ? null : vidyoReplayUrl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_tenant.portal_id
     *
     * @return the value of t_ext_vidyo_tenant.portal_id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Long getPortalId() {
        return portalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_tenant.portal_id
     *
     * @param portalId the value for t_ext_vidyo_tenant.portal_id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setPortalId(Long portalId) {
        this.portalId = portalId;
    }
}