package com.vccloud.portal.db.model;

public class TExtVidyoMember {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.allowCallDirect
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Boolean allowcalldirect;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.allowPersonalMeeting
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Boolean allowpersonalmeeting;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.description
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.displayName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String displayname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.email
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.extension
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String extension;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.groupName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String groupname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.language
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String language;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.locationTag
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String locationtag;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.name
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.password
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.proxyName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String proxyname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.remoteMemberId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Integer remotememberid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.roleName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private String rolename;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.thirdMemberId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Long thirdmemberid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_ext_vidyo_member.tenant_id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    private Long tenantId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.id
     *
     * @return the value of t_ext_vidyo_member.id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.id
     *
     * @param id the value for t_ext_vidyo_member.id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.allowCallDirect
     *
     * @return the value of t_ext_vidyo_member.allowCallDirect
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Boolean getAllowcalldirect() {
        return allowcalldirect;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.allowCallDirect
     *
     * @param allowcalldirect the value for t_ext_vidyo_member.allowCallDirect
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setAllowcalldirect(Boolean allowcalldirect) {
        this.allowcalldirect = allowcalldirect;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.allowPersonalMeeting
     *
     * @return the value of t_ext_vidyo_member.allowPersonalMeeting
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Boolean getAllowpersonalmeeting() {
        return allowpersonalmeeting;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.allowPersonalMeeting
     *
     * @param allowpersonalmeeting the value for t_ext_vidyo_member.allowPersonalMeeting
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setAllowpersonalmeeting(Boolean allowpersonalmeeting) {
        this.allowpersonalmeeting = allowpersonalmeeting;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.description
     *
     * @return the value of t_ext_vidyo_member.description
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.description
     *
     * @param description the value for t_ext_vidyo_member.description
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.displayName
     *
     * @return the value of t_ext_vidyo_member.displayName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.displayName
     *
     * @param displayname the value for t_ext_vidyo_member.displayName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname == null ? null : displayname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.email
     *
     * @return the value of t_ext_vidyo_member.email
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.email
     *
     * @param email the value for t_ext_vidyo_member.email
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.extension
     *
     * @return the value of t_ext_vidyo_member.extension
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.extension
     *
     * @param extension the value for t_ext_vidyo_member.extension
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.groupName
     *
     * @return the value of t_ext_vidyo_member.groupName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.groupName
     *
     * @param groupname the value for t_ext_vidyo_member.groupName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.language
     *
     * @return the value of t_ext_vidyo_member.language
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.language
     *
     * @param language the value for t_ext_vidyo_member.language
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.locationTag
     *
     * @return the value of t_ext_vidyo_member.locationTag
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getLocationtag() {
        return locationtag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.locationTag
     *
     * @param locationtag the value for t_ext_vidyo_member.locationTag
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setLocationtag(String locationtag) {
        this.locationtag = locationtag == null ? null : locationtag.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.name
     *
     * @return the value of t_ext_vidyo_member.name
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.name
     *
     * @param name the value for t_ext_vidyo_member.name
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.password
     *
     * @return the value of t_ext_vidyo_member.password
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.password
     *
     * @param password the value for t_ext_vidyo_member.password
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.proxyName
     *
     * @return the value of t_ext_vidyo_member.proxyName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getProxyname() {
        return proxyname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.proxyName
     *
     * @param proxyname the value for t_ext_vidyo_member.proxyName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setProxyname(String proxyname) {
        this.proxyname = proxyname == null ? null : proxyname.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.remoteMemberId
     *
     * @return the value of t_ext_vidyo_member.remoteMemberId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Integer getRemotememberid() {
        return remotememberid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.remoteMemberId
     *
     * @param remotememberid the value for t_ext_vidyo_member.remoteMemberId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setRemotememberid(Integer remotememberid) {
        this.remotememberid = remotememberid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.roleName
     *
     * @return the value of t_ext_vidyo_member.roleName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.roleName
     *
     * @param rolename the value for t_ext_vidyo_member.roleName
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.thirdMemberId
     *
     * @return the value of t_ext_vidyo_member.thirdMemberId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Long getThirdmemberid() {
        return thirdmemberid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.thirdMemberId
     *
     * @param thirdmemberid the value for t_ext_vidyo_member.thirdMemberId
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setThirdmemberid(Long thirdmemberid) {
        this.thirdmemberid = thirdmemberid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_ext_vidyo_member.tenant_id
     *
     * @return the value of t_ext_vidyo_member.tenant_id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_ext_vidyo_member.tenant_id
     *
     * @param tenantId the value for t_ext_vidyo_member.tenant_id
     *
     * @ibatorgenerated Wed Sep 04 14:33:40 CST 2013
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }
}