package com.vccloud.portal.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TLegacyExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    public TLegacyExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    protected TLegacyExample(TLegacyExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_legacy
     *
     * @ibatorgenerated Mon Nov 11 11:18:59 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return this;
        }

        public Criteria andUrlIn(List values) {
            addCriterion("url in", values, "url");
            return this;
        }

        public Criteria andUrlNotIn(List values) {
            addCriterion("url not in", values, "url");
            return this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return this;
        }

        public Criteria andLegacyNameIsNull() {
            addCriterion("legacy_name is null");
            return this;
        }

        public Criteria andLegacyNameIsNotNull() {
            addCriterion("legacy_name is not null");
            return this;
        }

        public Criteria andLegacyNameEqualTo(String value) {
            addCriterion("legacy_name =", value, "legacyName");
            return this;
        }

        public Criteria andLegacyNameNotEqualTo(String value) {
            addCriterion("legacy_name <>", value, "legacyName");
            return this;
        }

        public Criteria andLegacyNameGreaterThan(String value) {
            addCriterion("legacy_name >", value, "legacyName");
            return this;
        }

        public Criteria andLegacyNameGreaterThanOrEqualTo(String value) {
            addCriterion("legacy_name >=", value, "legacyName");
            return this;
        }

        public Criteria andLegacyNameLessThan(String value) {
            addCriterion("legacy_name <", value, "legacyName");
            return this;
        }

        public Criteria andLegacyNameLessThanOrEqualTo(String value) {
            addCriterion("legacy_name <=", value, "legacyName");
            return this;
        }

        public Criteria andLegacyNameLike(String value) {
            addCriterion("legacy_name like", value, "legacyName");
            return this;
        }

        public Criteria andLegacyNameNotLike(String value) {
            addCriterion("legacy_name not like", value, "legacyName");
            return this;
        }

        public Criteria andLegacyNameIn(List values) {
            addCriterion("legacy_name in", values, "legacyName");
            return this;
        }

        public Criteria andLegacyNameNotIn(List values) {
            addCriterion("legacy_name not in", values, "legacyName");
            return this;
        }

        public Criteria andLegacyNameBetween(String value1, String value2) {
            addCriterion("legacy_name between", value1, value2, "legacyName");
            return this;
        }

        public Criteria andLegacyNameNotBetween(String value1, String value2) {
            addCriterion("legacy_name not between", value1, value2, "legacyName");
            return this;
        }

        public Criteria andLegacyExtensionIsNull() {
            addCriterion("legacy_extension is null");
            return this;
        }

        public Criteria andLegacyExtensionIsNotNull() {
            addCriterion("legacy_extension is not null");
            return this;
        }

        public Criteria andLegacyExtensionEqualTo(String value) {
            addCriterion("legacy_extension =", value, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionNotEqualTo(String value) {
            addCriterion("legacy_extension <>", value, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionGreaterThan(String value) {
            addCriterion("legacy_extension >", value, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionGreaterThanOrEqualTo(String value) {
            addCriterion("legacy_extension >=", value, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionLessThan(String value) {
            addCriterion("legacy_extension <", value, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionLessThanOrEqualTo(String value) {
            addCriterion("legacy_extension <=", value, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionLike(String value) {
            addCriterion("legacy_extension like", value, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionNotLike(String value) {
            addCriterion("legacy_extension not like", value, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionIn(List values) {
            addCriterion("legacy_extension in", values, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionNotIn(List values) {
            addCriterion("legacy_extension not in", values, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionBetween(String value1, String value2) {
            addCriterion("legacy_extension between", value1, value2, "legacyExtension");
            return this;
        }

        public Criteria andLegacyExtensionNotBetween(String value1, String value2) {
            addCriterion("legacy_extension not between", value1, value2, "legacyExtension");
            return this;
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return this;
        }

        public Criteria andRoomIdEqualTo(String value) {
            addCriterion("room_id =", value, "roomId");
            return this;
        }

        public Criteria andRoomIdNotEqualTo(String value) {
            addCriterion("room_id <>", value, "roomId");
            return this;
        }

        public Criteria andRoomIdGreaterThan(String value) {
            addCriterion("room_id >", value, "roomId");
            return this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(String value) {
            addCriterion("room_id >=", value, "roomId");
            return this;
        }

        public Criteria andRoomIdLessThan(String value) {
            addCriterion("room_id <", value, "roomId");
            return this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(String value) {
            addCriterion("room_id <=", value, "roomId");
            return this;
        }

        public Criteria andRoomIdLike(String value) {
            addCriterion("room_id like", value, "roomId");
            return this;
        }

        public Criteria andRoomIdNotLike(String value) {
            addCriterion("room_id not like", value, "roomId");
            return this;
        }

        public Criteria andRoomIdIn(List values) {
            addCriterion("room_id in", values, "roomId");
            return this;
        }

        public Criteria andRoomIdNotIn(List values) {
            addCriterion("room_id not in", values, "roomId");
            return this;
        }

        public Criteria andRoomIdBetween(String value1, String value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return this;
        }

        public Criteria andRoomIdNotBetween(String value1, String value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("create_time in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("create_time not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeIn(List values) {
            addCriterion("update_time in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotIn(List values) {
            addCriterion("update_time not in", values, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return this;
        }
    }
}